// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBrowserBookmark = "browser_bookmarks"

// BrowserBookmark mapped from table <browser_bookmarks>
type BrowserBookmark struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_browser_bookmarks_owner_parent_order,priority:1;index:idx_browser_bookmarks_owner_match_key,priority:1" json:"id"`
	OwnerUserID int64          `gorm:"column:owner_user_id;type:bigint;not null;index:idx_browser_bookmarks_owner_parent_order,priority:2;index:idx_browser_bookmarks_owner_match_key,priority:2" json:"owner_user_id"`
	ParentID    *int64         `gorm:"column:parent_id;type:bigint;index:idx_browser_bookmarks_owner_parent_order,priority:3" json:"parent_id"`
	Kind        string         `gorm:"column:kind;type:character varying(16);not null" json:"kind"`
	Title       string         `gorm:"column:title;type:character varying(255);not null" json:"title"`
	URL         *string        `gorm:"column:url;type:character varying(2048)" json:"url"`
	URLMatchKey *string        `gorm:"column:url_match_key;type:character varying(2048);index:idx_browser_bookmarks_owner_match_key,priority:3" json:"url_match_key"`
	IconURL     *string        `gorm:"column:icon_url;type:character varying(2048)" json:"icon_url"`
	SortOrder   int32          `gorm:"column:sort_order;type:integer;not null;index:idx_browser_bookmarks_owner_parent_order,priority:4" json:"sort_order"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName BrowserBookmark's table name
func (*BrowserBookmark) TableName() string {
	return TableNameBrowserBookmark
}
