// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameBrowserFileMapping = "browser_file_mappings"

// BrowserFileMapping mapped from table <browser_file_mappings>
type BrowserFileMapping struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_browser_file_mappings_owner_ext_order,priority:2" json:"id"`
	FileExt     string         `gorm:"column:file_ext;type:character varying(64);not null;uniqueIndex:uq_browser_file_mappings_owner_ext_live,priority:1;index:idx_browser_file_mappings_owner_ext_order,priority:1" json:"file_ext"`
	SiteURL     string         `gorm:"column:site_url;type:character varying(2048);not null" json:"site_url"`
	OwnerUserID int64          `gorm:"column:owner_user_id;type:bigint;not null;uniqueIndex:uq_browser_file_mappings_owner_ext_live,priority:2;index:idx_browser_file_mappings_owner_ext_order,priority:3" json:"owner_user_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName BrowserFileMapping's table name
func (*BrowserFileMapping) TableName() string {
	return TableNameBrowserFileMapping
}
