// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLibrary = "libraries"

// Library mapped from table <libraries>
type Library struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_libraries_user_live,priority:1" json:"id"`
	UserID    *int64         `gorm:"column:user_id;type:bigint;index:idx_libraries_user_live,priority:2" json:"user_id"`
	Name      string         `gorm:"column:name;type:character varying(255);not null" json:"name"`
	Starred   bool           `gorm:"column:starred;type:boolean;not null" json:"starred"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Library's table name
func (*Library) TableName() string {
	return TableNameLibrary
}
