// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMigrationTask = "migration_tasks"

// MigrationTask mapped from table <migration_tasks>
type MigrationTask struct {
	ID               string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	ActorID          string     `gorm:"column:actor_id;type:text;not null;index:idx_migration_tasks_actor_library,priority:1" json:"actor_id"`
	LibraryID        int64      `gorm:"column:library_id;type:bigint;not null;index:idx_migration_tasks_actor_library,priority:2" json:"library_id"`
	RootNodeID       int64      `gorm:"column:root_node_id;type:bigint;not null" json:"root_node_id"`
	TargetProvider   string     `gorm:"column:target_provider;type:text;not null" json:"target_provider"`
	Status           string     `gorm:"column:status;type:text;not null;index:idx_migration_tasks_status,priority:1" json:"status"`
	TotalObjects     int32      `gorm:"column:total_objects;type:integer;not null" json:"total_objects"`
	CompletedObjects int32      `gorm:"column:completed_objects;type:integer;not null" json:"completed_objects"`
	FailedObjects    int32      `gorm:"column:failed_objects;type:integer;not null" json:"failed_objects"`
	SkippedObjects   int32      `gorm:"column:skipped_objects;type:integer;not null" json:"skipped_objects"`
	TotalBytes       int64      `gorm:"column:total_bytes;type:bigint;not null" json:"total_bytes"`
	TransferredBytes int64      `gorm:"column:transferred_bytes;type:bigint;not null" json:"transferred_bytes"`
	CurrentObjectKey string     `gorm:"column:current_object_key;type:text;not null" json:"current_object_key"`
	ErrorMessage     string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	CreatedAt        time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	StartedAt        *time.Time `gorm:"column:started_at;type:timestamp with time zone" json:"started_at"`
	FinishedAt       *time.Time `gorm:"column:finished_at;type:timestamp with time zone" json:"finished_at"`
}

// TableName MigrationTask's table name
func (*MigrationTask) TableName() string {
	return TableNameMigrationTask
}
