// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMigrationTaskItem = "migration_task_items"

// MigrationTaskItem mapped from table <migration_task_items>
type MigrationTaskItem struct {
	ID                    int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_migration_task_items_pending,priority:1" json:"id"`
	TaskID                string     `gorm:"column:task_id;type:text;not null;index:idx_migration_task_items_task,priority:1" json:"task_id"`
	StorageObjectID       int64      `gorm:"column:storage_object_id;type:bigint;not null" json:"storage_object_id"`
	SourceProvider        string     `gorm:"column:source_provider;type:text;not null" json:"source_provider"`
	SourceBucket          string     `gorm:"column:source_bucket;type:text;not null" json:"source_bucket"`
	SourceKey             string     `gorm:"column:source_key;type:text;not null" json:"source_key"`
	TargetStorageObjectID *int64     `gorm:"column:target_storage_object_id;type:bigint" json:"target_storage_object_id"`
	TargetKey             string     `gorm:"column:target_key;type:text;not null" json:"target_key"`
	FileSize              int64      `gorm:"column:file_size;type:bigint;not null" json:"file_size"`
	Status                string     `gorm:"column:status;type:text;not null;index:idx_migration_task_items_pending,priority:2;index:idx_migration_task_items_status,priority:1" json:"status"`
	ErrorMessage          string     `gorm:"column:error_message;type:text;not null" json:"error_message"`
	StartedAt             *time.Time `gorm:"column:started_at;type:timestamp with time zone" json:"started_at"`
	FinishedAt            *time.Time `gorm:"column:finished_at;type:timestamp with time zone" json:"finished_at"`
	CreatedAt             time.Time  `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName MigrationTaskItem's table name
func (*MigrationTaskItem) TableName() string {
	return TableNameMigrationTaskItem
}
