// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeFile = "node_files"

// NodeFile mapped from table <node_files>
type NodeFile struct {
	FileID          int64     `gorm:"column:file_id;type:bigint;primaryKey;index:idx_node_files_library,priority:1" json:"file_id"`
	LibraryID       int64     `gorm:"column:library_id;type:bigint;not null;index:idx_node_files_library,priority:2" json:"library_id"`
	StorageObjectID int64     `gorm:"column:storage_object_id;type:bigint;not null;index:idx_node_files_storage_object,priority:1" json:"storage_object_id"`
	MimeType        *string   `gorm:"column:mime_type;type:character varying(255);index:idx_node_files_mime_type,priority:1;comment:前端直接依赖：文件类型判断、预览分发、属性展示" json:"mime_type"` // 前端直接依赖：文件类型判断、预览分发、属性展示
	FileSize        int64     `gorm:"column:file_size;type:bigint;not null;comment:前端直接依赖：属性展示、列表/回收站展示" json:"file_size"`                                                     // 前端直接依赖：属性展示、列表/回收站展示
	ChecksumSha256  *string   `gorm:"column:checksum_sha256;type:character(64);index:idx_node_files_checksum,priority:1" json:"checksum_sha256"`
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName NodeFile's table name
func (*NodeFile) TableName() string {
	return TableNameNodeFile
}
