// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeResourceTarget = "node_resource_targets"

// NodeResourceTarget mapped from table <node_resource_targets>
type NodeResourceTarget struct {
	NodeID     int64     `gorm:"column:node_id;type:bigint;primaryKey;index:idx_node_resource_targets_target_node,priority:1;index:idx_node_resource_targets_library_target_node,priority:2" json:"node_id"`
	LibraryID  int64     `gorm:"column:library_id;type:bigint;not null;index:idx_node_resource_targets_library_target_node,priority:1" json:"library_id"`
	TargetKind string    `gorm:"column:target_kind;type:character varying(64);primaryKey;index:idx_node_resource_targets_target_node,priority:2;index:idx_node_resource_targets_library_target_node,priority:3" json:"target_kind"`
	Source     string    `gorm:"column:source;type:character varying(64);not null" json:"source"`
	UpdatedAt  time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName NodeResourceTarget's table name
func (*NodeResourceTarget) TableName() string {
	return TableNameNodeResourceTarget
}
