// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNode = "nodes"

// Node mapped from table <nodes>
type Node struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_nodes_live_builtin_type,priority:2;index:idx_nodes_live_children_order,priority:4;index:idx_nodes_recycle,priority:2;index:idx_nodes_live_children_name,priority:1" json:"id"`
	LibraryID   int64          `gorm:"column:library_id;type:bigint;not null;uniqueIndex:uq_nodes_live_sibling_visible_name,priority:1;index:idx_nodes_live_builtin_type,priority:3;index:idx_nodes_live_children_order,priority:5;index:idx_nodes_recycle,priority:3;index:idx_nodes_live_children_name,priority:2" json:"library_id"`
	ParentID    *int64         `gorm:"column:parent_id;type:bigint;uniqueIndex:uq_nodes_live_sibling_visible_name,priority:4;index:idx_nodes_live_children_order,priority:8;index:idx_nodes_live_children_name,priority:4;index:idx_nodes_parent_only,priority:1" json:"parent_id"`
	NodeType    int16          `gorm:"column:node_type;type:smallint;not null;uniqueIndex:uq_nodes_live_sibling_visible_name,priority:3;index:idx_nodes_live_children_order,priority:7;comment:0=folder, 1=file" json:"node_type"`                                                    // 0=folder, 1=file
	Name        string         `gorm:"column:name;type:character varying(255);not null;uniqueIndex:uq_nodes_live_sibling_visible_name,priority:2;index:idx_nodes_live_children_order,priority:6;index:idx_nodes_live_children_name,priority:3;comment:文件时不含后缀名；文件夹时为目录名" json:"name"` // 文件时不含后缀名；文件夹时为目录名
	Ext         *string        `gorm:"column:ext;type:character varying(32);index:idx_nodes_live_children_order,priority:3;comment:仅文件使用，建议不带点，例如 jpg / zip / go" json:"ext"`                                                                                                         // 仅文件使用，建议不带点，例如 jpg / zip / go
	BuiltInType string         `gorm:"column:built_in_type;type:character varying(32);not null;index:idx_nodes_live_builtin_type,priority:1;index:idx_nodes_live_children_order,priority:2;default:DEF;comment:开放字符串，当前核心值 DEF/COMIC/ASMR；写入前统一转大写" json:"built_in_type"`             // 开放字符串，当前核心值 DEF/COMIC/ASMR；写入前统一转大写
	ArchiveMode bool           `gorm:"column:archive_mode;type:boolean;not null;index:idx_nodes_live_children_order,priority:1;comment:当前主要用于目录浏览入口切换；数据库层不强制仅目录可开" json:"archive_mode"`                                                                                              // 当前主要用于目录浏览入口切换；数据库层不强制仅目录可开
	ViewMeta    string         `gorm:"column:view_meta;type:jsonb;not null;index:idx_nodes_view_meta_gin,priority:1;default:{};comment:可扩展视图配置 JSONB；当前稳定关键键包括 tagIds" json:"view_meta"`                                                                                              // 可扩展视图配置 JSONB；当前稳定关键键包括 tagIds
	SortOrder   int32          `gorm:"column:sort_order;type:integer;not null;index:idx_nodes_live_children_order,priority:9" json:"sort_order"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;index:idx_nodes_recycle,priority:1" json:"deleted_at"`
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName Node's table name
func (*Node) TableName() string {
	return TableNameNode
}
