// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeMutationReceipt = "node_mutation_receipts"

// NodeMutationReceipt mapped from table <node_mutation_receipts>
type NodeMutationReceipt struct {
	ActorID     string    `gorm:"column:actor_id;type:text;primaryKey" json:"actor_id"`
	OperationID string    `gorm:"column:operation_id;type:uuid;primaryKey" json:"operation_id"`
	LibraryID   int64     `gorm:"column:library_id;type:bigint;not null" json:"library_id"`
	Kind        string    `gorm:"column:kind;type:text;not null" json:"kind"`
	RequestHash string    `gorm:"column:request_hash;type:text;not null" json:"request_hash"`
	Result      string    `gorm:"column:result;type:jsonb;not null" json:"result"`
	CommittedAt time.Time `gorm:"column:committed_at;type:timestamp with time zone;not null;default:now()" json:"committed_at"`
}

// TableName NodeMutationReceipt's table name
func (*NodeMutationReceipt) TableName() string {
	return TableNameNodeMutationReceipt
}
