// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeTagRel = "node_tag_rel"

// NodeTagRel mapped from table <node_tag_rel>
type NodeTagRel struct {
	ID        int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	NodeID    int64     `gorm:"column:node_id;type:bigint;not null;index:idx_node_tag_rel_lib_tag_node,priority:2;index:idx_node_tag_rel_lib_node,priority:2" json:"node_id"`
	TagID     int64     `gorm:"column:tag_id;type:bigint;not null;index:idx_node_tag_rel_lib_tag_node,priority:3" json:"tag_id"`
	LibraryID int64     `gorm:"column:library_id;type:bigint;not null;index:idx_node_tag_rel_lib_tag_node,priority:1;index:idx_node_tag_rel_lib_node,priority:1" json:"library_id"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName NodeTagRel's table name
func (*NodeTagRel) TableName() string {
	return TableNameNodeTagRel
}
