// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameResourceMonitorSamples = "resource_monitor_samples"

// ResourceMonitorSamples mapped from table <resource_monitor_samples>
type ResourceMonitorSamples struct {
	ID                  int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ActorID             string    `gorm:"column:actor_id;type:text;not null;index:idx_resource_monitor_samples_actor_scope_time,priority:1" json:"actor_id"`
	Scope               string    `gorm:"column:scope;type:text;not null;index:idx_resource_monitor_samples_actor_scope_time,priority:4" json:"scope"`
	LibraryID           int64     `gorm:"column:library_id;type:bigint;not null;index:idx_resource_monitor_samples_actor_scope_time,priority:3" json:"library_id"`
	GeneratedAt         time.Time `gorm:"column:generated_at;type:timestamp with time zone;not null;index:idx_resource_monitor_samples_actor_scope_time,priority:2" json:"generated_at"`
	ProviderCount       int32     `gorm:"column:provider_count;type:integer;not null" json:"provider_count"`
	BucketCount         int32     `gorm:"column:bucket_count;type:integer;not null" json:"bucket_count"`
	ObjectCount         int64     `gorm:"column:object_count;type:bigint;not null" json:"object_count"`
	FileRefCount        int64     `gorm:"column:file_ref_count;type:bigint;not null" json:"file_ref_count"`
	PhysicalBytes       int64     `gorm:"column:physical_bytes;type:bigint;not null" json:"physical_bytes"`
	VisibleObjectCount  int64     `gorm:"column:visible_object_count;type:bigint;not null" json:"visible_object_count"`
	VisibleFileRefCount int64     `gorm:"column:visible_file_ref_count;type:bigint;not null" json:"visible_file_ref_count"`
	VisibleBytes        int64     `gorm:"column:visible_bytes;type:bigint;not null" json:"visible_bytes"`
	RecycleObjectCount  int64     `gorm:"column:recycle_object_count;type:bigint;not null" json:"recycle_object_count"`
	RecycleFileRefCount int64     `gorm:"column:recycle_file_ref_count;type:bigint;not null" json:"recycle_file_ref_count"`
	RecycleBytes        int64     `gorm:"column:recycle_bytes;type:bigint;not null" json:"recycle_bytes"`
	OrphanObjectCount   int64     `gorm:"column:orphan_object_count;type:bigint;not null" json:"orphan_object_count"`
	OrphanBytes         int64     `gorm:"column:orphan_bytes;type:bigint;not null" json:"orphan_bytes"`
	UnmatchedCount      int32     `gorm:"column:unmatched_count;type:integer;not null" json:"unmatched_count"`
	LegacyProviderCount int32     `gorm:"column:legacy_provider_count;type:integer;not null" json:"legacy_provider_count"`
	ProbeTotal          int32     `gorm:"column:probe_total;type:integer;not null" json:"probe_total"`
	ProbeOk             int32     `gorm:"column:probe_ok;type:integer;not null" json:"probe_ok"`
	ProbeError          int32     `gorm:"column:probe_error;type:integer;not null" json:"probe_error"`
	ProbeUnknown        int32     `gorm:"column:probe_unknown;type:integer;not null" json:"probe_unknown"`
	DistributionError   string    `gorm:"column:distribution_error;type:text;not null" json:"distribution_error"`
	SnapshotJSON        string    `gorm:"column:snapshot_json;type:jsonb;not null" json:"snapshot_json"`
	CreatedAt           time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;index:idx_resource_monitor_samples_created_at,priority:1;default:now()" json:"created_at"`
}

// TableName ResourceMonitorSamples's table name
func (*ResourceMonitorSamples) TableName() string {
	return TableNameResourceMonitorSamples
}
