// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameStorageObject = "storage_objects"

// StorageObject mapped from table <storage_objects>
type StorageObject struct {
	ID             int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_storage_objects_library_live,priority:1" json:"id"`
	LibraryID      int64          `gorm:"column:library_id;type:bigint;not null;index:idx_storage_objects_library_live,priority:2" json:"library_id"`
	Provider       string         `gorm:"column:provider;type:character varying(32);not null;uniqueIndex:uq_storage_objects_live_locator,priority:3" json:"provider"`
	Bucket         string         `gorm:"column:bucket;type:character varying(128);not null;uniqueIndex:uq_storage_objects_live_locator,priority:1" json:"bucket"`
	ObjectKey      string         `gorm:"column:object_key;type:text;not null;uniqueIndex:uq_storage_objects_live_locator,priority:2;comment:对象存储中的真实 key" json:"object_key"` // 对象存储中的真实 key
	VersionID      *string        `gorm:"column:version_id;type:character varying(255)" json:"version_id"`
	Etag           *string        `gorm:"column:etag;type:character varying(128)" json:"etag"`
	ChecksumSha256 *string        `gorm:"column:checksum_sha256;type:character(64);index:idx_storage_objects_checksum,priority:1" json:"checksum_sha256"`
	StorageClass   *string        `gorm:"column:storage_class;type:character varying(64)" json:"storage_class"`
	ContentLength  int64          `gorm:"column:content_length;type:bigint;not null" json:"content_length"`
	ContentType    *string        `gorm:"column:content_type;type:character varying(255)" json:"content_type"`
	Extra          string         `gorm:"column:extra;type:jsonb;not null;default:{};comment:厂商扩展字段" json:"extra"` // 厂商扩展字段
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName StorageObject's table name
func (*StorageObject) TableName() string {
	return TableNameStorageObject
}
