// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTagBindPolicy = "tag_bind_policies"

// TagBindPolicy mapped from table <tag_bind_policies>
type TagBindPolicy struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TagID      int64     `gorm:"column:tag_id;type:bigint;not null;index:idx_tag_bind_policies_target_tag,priority:1;index:idx_tag_bind_policies_tag,priority:1" json:"tag_id"`
	TargetKind string    `gorm:"column:target_kind;type:character varying(64);not null;index:idx_tag_bind_policies_target_tag,priority:2" json:"target_kind"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
}

// TableName TagBindPolicy's table name
func (*TagBindPolicy) TableName() string {
	return TableNameTagBindPolicy
}
