// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTagTargetKind = "tag_target_kinds"

// TagTargetKind mapped from table <tag_target_kinds>
type TagTargetKind struct {
	Key          string    `gorm:"column:key;type:character varying(64);primaryKey;index:idx_tag_target_kinds_resource_order,priority:1" json:"key"`
	Label        string    `gorm:"column:label;type:character varying(64);not null" json:"label"`
	ResourceKind string    `gorm:"column:resource_kind;type:character varying(64);not null;index:idx_tag_target_kinds_resource_order,priority:2" json:"resource_kind"`
	SortOrder    int32     `gorm:"column:sort_order;type:integer;not null;index:idx_tag_target_kinds_resource_order,priority:3" json:"sort_order"`
	Enabled      bool      `gorm:"column:enabled;type:boolean;not null;default:true" json:"enabled"`
	Description  *string   `gorm:"column:description;type:character varying(255)" json:"description"`
	CreatedAt    time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName TagTargetKind's table name
func (*TagTargetKind) TableName() string {
	return TableNameTagTargetKind
}
