// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTagAlias = "tag_aliases"

// TagAlias mapped from table <tag_aliases>
type TagAlias struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	TagID           int64          `gorm:"column:tag_id;type:bigint;not null;uniqueIndex:uq_tag_aliases_tag_alias_live,priority:2;index:idx_tag_aliases_tag,priority:1" json:"tag_id"`
	Alias_          string         `gorm:"column:alias;type:character varying;not null" json:"alias"`
	NormalizedAlias string         `gorm:"column:normalized_alias;type:character varying;not null;uniqueIndex:uq_tag_aliases_tag_alias_live,priority:1;index:idx_tag_aliases_owner_alias,priority:1" json:"normalized_alias"`
	OwnerUserID     *int64         `gorm:"column:owner_user_id;type:bigint;index:idx_tag_aliases_owner_alias,priority:2" json:"owner_user_id"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
}

// TableName TagAlias's table name
func (*TagAlias) TableName() string {
	return TableNameTagAlias
}
