// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;index:idx_tags_type_target_order,priority:1;index:idx_tags_scope_resource_order,priority:2;index:idx_tags_owner_type_order,priority:1;index:idx_tags_owner_scope_dimension_order,priority:2" json:"id"`
	Name         string         `gorm:"column:name;type:character varying(64);not null;uniqueIndex:uq_tags_scope_name_live,priority:2" json:"name"`
	Type         string         `gorm:"column:type;type:character varying(32);not null;uniqueIndex:uq_tags_scope_name_live,priority:4;index:idx_tags_type_target_order,priority:4;index:idx_tags_owner_type_order,priority:4;default:GENERAL" json:"type"`
	TargetKey    *string        `gorm:"column:target_key;type:character varying(64);index:idx_tags_type_target_order,priority:3" json:"target_key"`
	OwnerUserID  *int64         `gorm:"column:owner_user_id;type:bigint;index:idx_tags_owner_type_order,priority:2;index:idx_tags_owner_scope_dimension_order,priority:3" json:"owner_user_id"`
	Color        string         `gorm:"column:color;type:character varying(32);not null;default:#4F8CFF" json:"color"`
	TextColor    *string        `gorm:"column:text_color;type:character varying(32)" json:"text_color"`
	SortOrder    int32          `gorm:"column:sort_order;type:integer;not null;index:idx_tags_type_target_order,priority:2;index:idx_tags_scope_resource_order,priority:5;index:idx_tags_owner_type_order,priority:3;index:idx_tags_owner_scope_dimension_order,priority:6" json:"sort_order"`
	Enabled      bool           `gorm:"column:enabled;type:boolean;not null;default:true" json:"enabled"`
	Description  *string        `gorm:"column:description;type:character varying(255)" json:"description"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	Scope        string         `gorm:"column:scope;type:character varying;not null;uniqueIndex:uq_tags_scope_name_live,priority:3;index:idx_tags_scope_resource_order,priority:4;index:idx_tags_owner_scope_dimension_order,priority:5;default:resource" json:"scope"`
	Dimension    string         `gorm:"column:dimension;type:character varying;not null;uniqueIndex:uq_tags_scope_name_live,priority:1;index:idx_tags_scope_resource_order,priority:1;index:idx_tags_owner_scope_dimension_order,priority:1;default:custom" json:"dimension"`
	ResourceKind *string        `gorm:"column:resource_kind;type:character varying;index:idx_tags_scope_resource_order,priority:3;index:idx_tags_owner_scope_dimension_order,priority:4" json:"resource_kind"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
