// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPreference = "user_preferences"

// UserPreference mapped from table <user_preferences>
type UserPreference struct {
	UserID        int64     `gorm:"column:user_id;type:bigint;primaryKey" json:"user_id"`
	Namespace     string    `gorm:"column:namespace;type:character varying(64);primaryKey;comment:偏好命名空间，例如 tool-workspace" json:"namespace"` // 偏好命名空间，例如 tool-workspace
	Data          string    `gorm:"column:data;type:jsonb;not null;default:{};comment:命名空间内的 JSON 对象数据" json:"data"`                          // 命名空间内的 JSON 对象数据
	SchemaVersion int32     `gorm:"column:schema_version;type:integer;not null;default:1;comment:data 结构版本" json:"schema_version"`            // data 结构版本
	Revision      int64     `gorm:"column:revision;type:bigint;not null;default:1;comment:乐观并发控制版本" json:"revision"`                          // 乐观并发控制版本
	CreatedAt     time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName UserPreference's table name
func (*UserPreference) TableName() string {
	return TableNameUserPreference
}
