// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Username     string         `gorm:"column:username;type:character varying(50);not null" json:"username"`
	Nickname     *string        `gorm:"column:nickname;type:character varying(100)" json:"nickname"`
	PasswordHash string         `gorm:"column:password_hash;type:character varying(255);not null" json:"password_hash"`
	Phone        *string        `gorm:"column:phone;type:character varying(20)" json:"phone"`
	Email        *string        `gorm:"column:email;type:character varying(100);index:idx_users_email,priority:1" json:"email"`
	Ext          string         `gorm:"column:ext;type:jsonb;not null;default:{};comment:扩展信息 JSONB" json:"ext"` // 扩展信息 JSONB
	Status       int16          `gorm:"column:status;type:smallint;not null;default:1" json:"status"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
