// Code generated by Wire. DO NOT EDIT.

package bootstrap

import (
	"omniflow-go/internal/app"
	"omniflow-go/internal/audit"
	"omniflow-go/internal/authz"
	"omniflow-go/internal/config"
	"omniflow-go/internal/repository"
	"omniflow-go/internal/server"
	httpHandler "omniflow-go/internal/transport/http/handler"
	httpRouter "omniflow-go/internal/transport/http/router"
	"omniflow-go/internal/usecase"
)

func InitializeApplication(configPath string) (*app.App, func(), error) {
	cfg, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}

	logger := NewLogger(cfg)
	allowAll := authz.NewAllowAll()
	logSink := audit.NewLogSink(logger)

	database, databaseCleanup, err := NewDatabase(cfg, logger)
	if err != nil {
		return nil, nil, err
	}

	redisClient, redisCleanup, err := NewRedis(cfg)
	if err != nil {
		databaseCleanup()
		return nil, nil, err
	}

	objectStorage, objectStorageCleanup, err := repository.NewObjectStorage(cfg)
	if err != nil {
		redisCleanup()
		databaseCleanup()
		return nil, nil, err
	}

	userRepository := repository.NewUserRepository(database)
	libraryRepository := repository.NewLibraryRepository(database)
	nodeRepository := repository.NewNodeRepository(database)
	tagRepository := repository.NewTagRepository(database)
	sessionRepository := repository.NewSessionRepository(redisClient)
	transactor := repository.NewTransactor(database)

	healthUseCase := usecase.NewHealthUseCase(cfg)
	authUseCase := usecase.NewAuthUseCase(userRepository, sessionRepository, logSink)
	userUseCase := usecase.NewUserUseCase(userRepository, objectStorage, transactor, logSink)
	libraryUseCase := usecase.NewLibraryUseCase(libraryRepository, transactor, allowAll, logSink)
	nodeUseCase := usecase.NewNodeUseCase(nodeRepository, transactor, allowAll, logSink)
	directoryUseCase := usecase.NewDirectoryUseCase(nodeUseCase, objectStorage, allowAll, logSink)
	fileUseCase := usecase.NewFileUseCase(objectStorage)
	tagUseCase := usecase.NewTagUseCase(tagRepository, transactor)

	healthHandler := httpHandler.NewHealthHandler(healthUseCase)
	authHandler := httpHandler.NewAuthHandler(authUseCase)
	userHandler := httpHandler.NewUserHandler(userUseCase)
	libraryHandler := httpHandler.NewLibraryHandler(libraryUseCase)
	nodeHandler := httpHandler.NewNodeHandler(nodeUseCase)
	directoryHandler := httpHandler.NewDirectoryHandler(directoryUseCase)
	fileHandler := httpHandler.NewFileHandler(fileUseCase)
	tagHandler := httpHandler.NewTagHandler(tagUseCase)

	engine := httpRouter.New(cfg, logger, healthHandler, authHandler, userHandler, libraryHandler, nodeHandler, directoryHandler, fileHandler, tagHandler)
	httpServer := server.NewHTTPServer(cfg, engine, logger)
	application := app.New(cfg, logger, httpServer)

	cleanup := func() {
		objectStorageCleanup()
		redisCleanup()
		databaseCleanup()
	}

	return application, cleanup, nil
}
