// Code generated by Wire. DO NOT EDIT.

package bootstrap

import (
	"omniflow-go/internal/app"
	"omniflow-go/internal/audit"
	"omniflow-go/internal/authz"
	"omniflow-go/internal/config"
	"omniflow-go/internal/repository"
	"omniflow-go/internal/server"
	"omniflow-go/internal/storage"
	httpHandler "omniflow-go/internal/transport/http/handler"
	httpRouter "omniflow-go/internal/transport/http/router"
	"omniflow-go/internal/usecase"
)

func InitializeApplication(configPath string) (*app.App, func(), error) {
	cfg, err := config.Load(configPath)
	if err != nil {
		return nil, nil, err
	}

	logger := NewLogger(cfg)
	allowAll := authz.NewAllowAll()
	logSink := audit.NewLogSink(logger)

	database, databaseCleanup, err := NewDatabase(cfg, logger)
	if err != nil {
		return nil, nil, err
	}

	redisClient, redisCleanup, err := NewRedis(cfg)
	if err != nil {
		databaseCleanup()
		return nil, nil, err
	}

	minioStore, minioCleanup, err := storage.NewMinIOStore(cfg)
	if err != nil {
		redisCleanup()
		databaseCleanup()
		return nil, nil, err
	}

	userRepository := repository.NewUserRepository(database)
	libraryRepository := repository.NewLibraryRepository(database)
	nodeRepository := repository.NewNodeRepository(database)

	healthUseCase := usecase.NewHealthUseCase(cfg)
	authUseCase := usecase.NewAuthUseCase(userRepository, logSink, redisClient)
	userUseCase := usecase.NewUserUseCase(userRepository, redisClient, minioStore, logSink)
	libraryUseCase := usecase.NewLibraryUseCase(libraryRepository, allowAll, logSink)
	nodeUseCase := usecase.NewNodeUseCase(nodeRepository, allowAll, logSink)
	directoryUseCase := usecase.NewDirectoryUseCase(nodeUseCase, minioStore, allowAll, logSink)
	fileUseCase := usecase.NewFileUseCase(minioStore)
	tagUseCase := usecase.NewTagUseCase()

	healthHandler := httpHandler.NewHealthHandler(healthUseCase)
	authHandler := httpHandler.NewAuthHandler(authUseCase)
	userHandler := httpHandler.NewUserHandler(userUseCase)
	libraryHandler := httpHandler.NewLibraryHandler(libraryUseCase)
	nodeHandler := httpHandler.NewNodeHandler(nodeUseCase)
	directoryHandler := httpHandler.NewDirectoryHandler(directoryUseCase)
	fileHandler := httpHandler.NewFileHandler(fileUseCase)
	tagHandler := httpHandler.NewTagHandler(tagUseCase)

	engine := httpRouter.New(cfg, logger, healthHandler, authHandler, userHandler, libraryHandler, nodeHandler, directoryHandler, fileHandler, tagHandler)
	httpServer := server.NewHTTPServer(cfg, engine, logger)
	application := app.New(cfg, logger, httpServer)

	cleanup := func() {
		minioCleanup()
		redisCleanup()
		databaseCleanup()
	}

	return application, cleanup, nil
}
