// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newBrowserFileMapping(db *gorm.DB, opts ...gen.DOOption) browserFileMapping {
	_browserFileMapping := browserFileMapping{}

	_browserFileMapping.browserFileMappingDo.UseDB(db, opts...)
	_browserFileMapping.browserFileMappingDo.UseModel(&model.BrowserFileMapping{})

	tableName := _browserFileMapping.browserFileMappingDo.TableName()
	_browserFileMapping.ALL = field.NewAsterisk(tableName)
	_browserFileMapping.ID = field.NewInt64(tableName, "id")
	_browserFileMapping.FileExt = field.NewString(tableName, "file_ext")
	_browserFileMapping.SiteURL = field.NewString(tableName, "site_url")
	_browserFileMapping.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_browserFileMapping.CreatedAt = field.NewTime(tableName, "created_at")
	_browserFileMapping.UpdatedAt = field.NewTime(tableName, "updated_at")
	_browserFileMapping.DeletedAt = field.NewField(tableName, "deleted_at")

	_browserFileMapping.fillFieldMap()

	return _browserFileMapping
}

type browserFileMapping struct {
	browserFileMappingDo browserFileMappingDo

	ALL         field.Asterisk
	ID          field.Int64
	FileExt     field.String
	SiteURL     field.String
	OwnerUserID field.Int64
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (b browserFileMapping) Table(newTableName string) *browserFileMapping {
	b.browserFileMappingDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b browserFileMapping) As(alias string) *browserFileMapping {
	b.browserFileMappingDo.DO = *(b.browserFileMappingDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *browserFileMapping) updateTableName(table string) *browserFileMapping {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.FileExt = field.NewString(table, "file_ext")
	b.SiteURL = field.NewString(table, "site_url")
	b.OwnerUserID = field.NewInt64(table, "owner_user_id")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.DeletedAt = field.NewField(table, "deleted_at")

	b.fillFieldMap()

	return b
}

func (b *browserFileMapping) WithContext(ctx context.Context) IBrowserFileMappingDo {
	return b.browserFileMappingDo.WithContext(ctx)
}

func (b browserFileMapping) TableName() string { return b.browserFileMappingDo.TableName() }

func (b browserFileMapping) Alias() string { return b.browserFileMappingDo.Alias() }

func (b browserFileMapping) Columns(cols ...field.Expr) gen.Columns {
	return b.browserFileMappingDo.Columns(cols...)
}

func (b *browserFileMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *browserFileMapping) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 7)
	b.fieldMap["id"] = b.ID
	b.fieldMap["file_ext"] = b.FileExt
	b.fieldMap["site_url"] = b.SiteURL
	b.fieldMap["owner_user_id"] = b.OwnerUserID
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["deleted_at"] = b.DeletedAt
}

func (b browserFileMapping) clone(db *gorm.DB) browserFileMapping {
	b.browserFileMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b browserFileMapping) replaceDB(db *gorm.DB) browserFileMapping {
	b.browserFileMappingDo.ReplaceDB(db)
	return b
}

type browserFileMappingDo struct{ gen.DO }

type IBrowserFileMappingDo interface {
	gen.SubQuery
	Debug() IBrowserFileMappingDo
	WithContext(ctx context.Context) IBrowserFileMappingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBrowserFileMappingDo
	WriteDB() IBrowserFileMappingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBrowserFileMappingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBrowserFileMappingDo
	Not(conds ...gen.Condition) IBrowserFileMappingDo
	Or(conds ...gen.Condition) IBrowserFileMappingDo
	Select(conds ...field.Expr) IBrowserFileMappingDo
	Where(conds ...gen.Condition) IBrowserFileMappingDo
	Order(conds ...field.Expr) IBrowserFileMappingDo
	Distinct(cols ...field.Expr) IBrowserFileMappingDo
	Omit(cols ...field.Expr) IBrowserFileMappingDo
	Join(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo
	Group(cols ...field.Expr) IBrowserFileMappingDo
	Having(conds ...gen.Condition) IBrowserFileMappingDo
	Limit(limit int) IBrowserFileMappingDo
	Offset(offset int) IBrowserFileMappingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBrowserFileMappingDo
	Unscoped() IBrowserFileMappingDo
	Create(values ...*model.BrowserFileMapping) error
	CreateInBatches(values []*model.BrowserFileMapping, batchSize int) error
	Save(values ...*model.BrowserFileMapping) error
	First() (*model.BrowserFileMapping, error)
	Take() (*model.BrowserFileMapping, error)
	Last() (*model.BrowserFileMapping, error)
	Find() ([]*model.BrowserFileMapping, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BrowserFileMapping, err error)
	FindInBatches(result *[]*model.BrowserFileMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BrowserFileMapping) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBrowserFileMappingDo
	Assign(attrs ...field.AssignExpr) IBrowserFileMappingDo
	Joins(fields ...field.RelationField) IBrowserFileMappingDo
	Preload(fields ...field.RelationField) IBrowserFileMappingDo
	FirstOrInit() (*model.BrowserFileMapping, error)
	FirstOrCreate() (*model.BrowserFileMapping, error)
	FindByPage(offset int, limit int) (result []*model.BrowserFileMapping, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBrowserFileMappingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b browserFileMappingDo) Debug() IBrowserFileMappingDo {
	return b.withDO(b.DO.Debug())
}

func (b browserFileMappingDo) WithContext(ctx context.Context) IBrowserFileMappingDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b browserFileMappingDo) ReadDB() IBrowserFileMappingDo {
	return b.Clauses(dbresolver.Read)
}

func (b browserFileMappingDo) WriteDB() IBrowserFileMappingDo {
	return b.Clauses(dbresolver.Write)
}

func (b browserFileMappingDo) Session(config *gorm.Session) IBrowserFileMappingDo {
	return b.withDO(b.DO.Session(config))
}

func (b browserFileMappingDo) Clauses(conds ...clause.Expression) IBrowserFileMappingDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b browserFileMappingDo) Returning(value interface{}, columns ...string) IBrowserFileMappingDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b browserFileMappingDo) Not(conds ...gen.Condition) IBrowserFileMappingDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b browserFileMappingDo) Or(conds ...gen.Condition) IBrowserFileMappingDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b browserFileMappingDo) Select(conds ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b browserFileMappingDo) Where(conds ...gen.Condition) IBrowserFileMappingDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b browserFileMappingDo) Order(conds ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b browserFileMappingDo) Distinct(cols ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b browserFileMappingDo) Omit(cols ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b browserFileMappingDo) Join(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b browserFileMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b browserFileMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b browserFileMappingDo) Group(cols ...field.Expr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b browserFileMappingDo) Having(conds ...gen.Condition) IBrowserFileMappingDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b browserFileMappingDo) Limit(limit int) IBrowserFileMappingDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b browserFileMappingDo) Offset(offset int) IBrowserFileMappingDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b browserFileMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBrowserFileMappingDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b browserFileMappingDo) Unscoped() IBrowserFileMappingDo {
	return b.withDO(b.DO.Unscoped())
}

func (b browserFileMappingDo) Create(values ...*model.BrowserFileMapping) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b browserFileMappingDo) CreateInBatches(values []*model.BrowserFileMapping, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b browserFileMappingDo) Save(values ...*model.BrowserFileMapping) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b browserFileMappingDo) First() (*model.BrowserFileMapping, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserFileMapping), nil
	}
}

func (b browserFileMappingDo) Take() (*model.BrowserFileMapping, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserFileMapping), nil
	}
}

func (b browserFileMappingDo) Last() (*model.BrowserFileMapping, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserFileMapping), nil
	}
}

func (b browserFileMappingDo) Find() ([]*model.BrowserFileMapping, error) {
	result, err := b.DO.Find()
	return result.([]*model.BrowserFileMapping), err
}

func (b browserFileMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BrowserFileMapping, err error) {
	buf := make([]*model.BrowserFileMapping, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b browserFileMappingDo) FindInBatches(result *[]*model.BrowserFileMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b browserFileMappingDo) Attrs(attrs ...field.AssignExpr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b browserFileMappingDo) Assign(attrs ...field.AssignExpr) IBrowserFileMappingDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b browserFileMappingDo) Joins(fields ...field.RelationField) IBrowserFileMappingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b browserFileMappingDo) Preload(fields ...field.RelationField) IBrowserFileMappingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b browserFileMappingDo) FirstOrInit() (*model.BrowserFileMapping, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserFileMapping), nil
	}
}

func (b browserFileMappingDo) FirstOrCreate() (*model.BrowserFileMapping, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserFileMapping), nil
	}
}

func (b browserFileMappingDo) FindByPage(offset int, limit int) (result []*model.BrowserFileMapping, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b browserFileMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b browserFileMappingDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b browserFileMappingDo) Delete(models ...*model.BrowserFileMapping) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *browserFileMappingDo) withDO(do gen.Dao) *browserFileMappingDo {
	b.DO = *do.(*gen.DO)
	return b
}
