// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newBrowserBookmark(db *gorm.DB, opts ...gen.DOOption) browserBookmark {
	_browserBookmark := browserBookmark{}

	_browserBookmark.browserBookmarkDo.UseDB(db, opts...)
	_browserBookmark.browserBookmarkDo.UseModel(&model.BrowserBookmark{})

	tableName := _browserBookmark.browserBookmarkDo.TableName()
	_browserBookmark.ALL = field.NewAsterisk(tableName)
	_browserBookmark.ID = field.NewInt64(tableName, "id")
	_browserBookmark.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_browserBookmark.ParentID = field.NewInt64(tableName, "parent_id")
	_browserBookmark.Kind = field.NewString(tableName, "kind")
	_browserBookmark.Title = field.NewString(tableName, "title")
	_browserBookmark.URL = field.NewString(tableName, "url")
	_browserBookmark.URLMatchKey = field.NewString(tableName, "url_match_key")
	_browserBookmark.IconURL = field.NewString(tableName, "icon_url")
	_browserBookmark.SortOrder = field.NewInt32(tableName, "sort_order")
	_browserBookmark.CreatedAt = field.NewTime(tableName, "created_at")
	_browserBookmark.UpdatedAt = field.NewTime(tableName, "updated_at")
	_browserBookmark.DeletedAt = field.NewField(tableName, "deleted_at")

	_browserBookmark.fillFieldMap()

	return _browserBookmark
}

type browserBookmark struct {
	browserBookmarkDo browserBookmarkDo

	ALL         field.Asterisk
	ID          field.Int64
	OwnerUserID field.Int64
	ParentID    field.Int64
	Kind        field.String
	Title       field.String
	URL         field.String
	URLMatchKey field.String
	IconURL     field.String
	SortOrder   field.Int32
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field

	fieldMap map[string]field.Expr
}

func (b browserBookmark) Table(newTableName string) *browserBookmark {
	b.browserBookmarkDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b browserBookmark) As(alias string) *browserBookmark {
	b.browserBookmarkDo.DO = *(b.browserBookmarkDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *browserBookmark) updateTableName(table string) *browserBookmark {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewInt64(table, "id")
	b.OwnerUserID = field.NewInt64(table, "owner_user_id")
	b.ParentID = field.NewInt64(table, "parent_id")
	b.Kind = field.NewString(table, "kind")
	b.Title = field.NewString(table, "title")
	b.URL = field.NewString(table, "url")
	b.URLMatchKey = field.NewString(table, "url_match_key")
	b.IconURL = field.NewString(table, "icon_url")
	b.SortOrder = field.NewInt32(table, "sort_order")
	b.CreatedAt = field.NewTime(table, "created_at")
	b.UpdatedAt = field.NewTime(table, "updated_at")
	b.DeletedAt = field.NewField(table, "deleted_at")

	b.fillFieldMap()

	return b
}

func (b *browserBookmark) WithContext(ctx context.Context) IBrowserBookmarkDo {
	return b.browserBookmarkDo.WithContext(ctx)
}

func (b browserBookmark) TableName() string { return b.browserBookmarkDo.TableName() }

func (b browserBookmark) Alias() string { return b.browserBookmarkDo.Alias() }

func (b browserBookmark) Columns(cols ...field.Expr) gen.Columns {
	return b.browserBookmarkDo.Columns(cols...)
}

func (b *browserBookmark) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *browserBookmark) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 12)
	b.fieldMap["id"] = b.ID
	b.fieldMap["owner_user_id"] = b.OwnerUserID
	b.fieldMap["parent_id"] = b.ParentID
	b.fieldMap["kind"] = b.Kind
	b.fieldMap["title"] = b.Title
	b.fieldMap["url"] = b.URL
	b.fieldMap["url_match_key"] = b.URLMatchKey
	b.fieldMap["icon_url"] = b.IconURL
	b.fieldMap["sort_order"] = b.SortOrder
	b.fieldMap["created_at"] = b.CreatedAt
	b.fieldMap["updated_at"] = b.UpdatedAt
	b.fieldMap["deleted_at"] = b.DeletedAt
}

func (b browserBookmark) clone(db *gorm.DB) browserBookmark {
	b.browserBookmarkDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b browserBookmark) replaceDB(db *gorm.DB) browserBookmark {
	b.browserBookmarkDo.ReplaceDB(db)
	return b
}

type browserBookmarkDo struct{ gen.DO }

type IBrowserBookmarkDo interface {
	gen.SubQuery
	Debug() IBrowserBookmarkDo
	WithContext(ctx context.Context) IBrowserBookmarkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBrowserBookmarkDo
	WriteDB() IBrowserBookmarkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBrowserBookmarkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBrowserBookmarkDo
	Not(conds ...gen.Condition) IBrowserBookmarkDo
	Or(conds ...gen.Condition) IBrowserBookmarkDo
	Select(conds ...field.Expr) IBrowserBookmarkDo
	Where(conds ...gen.Condition) IBrowserBookmarkDo
	Order(conds ...field.Expr) IBrowserBookmarkDo
	Distinct(cols ...field.Expr) IBrowserBookmarkDo
	Omit(cols ...field.Expr) IBrowserBookmarkDo
	Join(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo
	Group(cols ...field.Expr) IBrowserBookmarkDo
	Having(conds ...gen.Condition) IBrowserBookmarkDo
	Limit(limit int) IBrowserBookmarkDo
	Offset(offset int) IBrowserBookmarkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBrowserBookmarkDo
	Unscoped() IBrowserBookmarkDo
	Create(values ...*model.BrowserBookmark) error
	CreateInBatches(values []*model.BrowserBookmark, batchSize int) error
	Save(values ...*model.BrowserBookmark) error
	First() (*model.BrowserBookmark, error)
	Take() (*model.BrowserBookmark, error)
	Last() (*model.BrowserBookmark, error)
	Find() ([]*model.BrowserBookmark, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BrowserBookmark, err error)
	FindInBatches(result *[]*model.BrowserBookmark, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BrowserBookmark) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBrowserBookmarkDo
	Assign(attrs ...field.AssignExpr) IBrowserBookmarkDo
	Joins(fields ...field.RelationField) IBrowserBookmarkDo
	Preload(fields ...field.RelationField) IBrowserBookmarkDo
	FirstOrInit() (*model.BrowserBookmark, error)
	FirstOrCreate() (*model.BrowserBookmark, error)
	FindByPage(offset int, limit int) (result []*model.BrowserBookmark, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBrowserBookmarkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b browserBookmarkDo) Debug() IBrowserBookmarkDo {
	return b.withDO(b.DO.Debug())
}

func (b browserBookmarkDo) WithContext(ctx context.Context) IBrowserBookmarkDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b browserBookmarkDo) ReadDB() IBrowserBookmarkDo {
	return b.Clauses(dbresolver.Read)
}

func (b browserBookmarkDo) WriteDB() IBrowserBookmarkDo {
	return b.Clauses(dbresolver.Write)
}

func (b browserBookmarkDo) Session(config *gorm.Session) IBrowserBookmarkDo {
	return b.withDO(b.DO.Session(config))
}

func (b browserBookmarkDo) Clauses(conds ...clause.Expression) IBrowserBookmarkDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b browserBookmarkDo) Returning(value interface{}, columns ...string) IBrowserBookmarkDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b browserBookmarkDo) Not(conds ...gen.Condition) IBrowserBookmarkDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b browserBookmarkDo) Or(conds ...gen.Condition) IBrowserBookmarkDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b browserBookmarkDo) Select(conds ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b browserBookmarkDo) Where(conds ...gen.Condition) IBrowserBookmarkDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b browserBookmarkDo) Order(conds ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b browserBookmarkDo) Distinct(cols ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b browserBookmarkDo) Omit(cols ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b browserBookmarkDo) Join(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b browserBookmarkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b browserBookmarkDo) RightJoin(table schema.Tabler, on ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b browserBookmarkDo) Group(cols ...field.Expr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b browserBookmarkDo) Having(conds ...gen.Condition) IBrowserBookmarkDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b browserBookmarkDo) Limit(limit int) IBrowserBookmarkDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b browserBookmarkDo) Offset(offset int) IBrowserBookmarkDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b browserBookmarkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBrowserBookmarkDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b browserBookmarkDo) Unscoped() IBrowserBookmarkDo {
	return b.withDO(b.DO.Unscoped())
}

func (b browserBookmarkDo) Create(values ...*model.BrowserBookmark) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b browserBookmarkDo) CreateInBatches(values []*model.BrowserBookmark, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b browserBookmarkDo) Save(values ...*model.BrowserBookmark) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b browserBookmarkDo) First() (*model.BrowserBookmark, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserBookmark), nil
	}
}

func (b browserBookmarkDo) Take() (*model.BrowserBookmark, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserBookmark), nil
	}
}

func (b browserBookmarkDo) Last() (*model.BrowserBookmark, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserBookmark), nil
	}
}

func (b browserBookmarkDo) Find() ([]*model.BrowserBookmark, error) {
	result, err := b.DO.Find()
	return result.([]*model.BrowserBookmark), err
}

func (b browserBookmarkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BrowserBookmark, err error) {
	buf := make([]*model.BrowserBookmark, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b browserBookmarkDo) FindInBatches(result *[]*model.BrowserBookmark, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b browserBookmarkDo) Attrs(attrs ...field.AssignExpr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b browserBookmarkDo) Assign(attrs ...field.AssignExpr) IBrowserBookmarkDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b browserBookmarkDo) Joins(fields ...field.RelationField) IBrowserBookmarkDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b browserBookmarkDo) Preload(fields ...field.RelationField) IBrowserBookmarkDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b browserBookmarkDo) FirstOrInit() (*model.BrowserBookmark, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserBookmark), nil
	}
}

func (b browserBookmarkDo) FirstOrCreate() (*model.BrowserBookmark, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BrowserBookmark), nil
	}
}

func (b browserBookmarkDo) FindByPage(offset int, limit int) (result []*model.BrowserBookmark, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b browserBookmarkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b browserBookmarkDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b browserBookmarkDo) Delete(models ...*model.BrowserBookmark) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *browserBookmarkDo) withDO(do gen.Dao) *browserBookmarkDo {
	b.DO = *do.(*gen.DO)
	return b
}
