// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	BrowserFileMapping *browserFileMapping
	Library            *library
	Node               *node
	NodeFile           *nodeFile
	StorageObject      *storageObject
	User               *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	BrowserFileMapping = &Q.BrowserFileMapping
	Library = &Q.Library
	Node = &Q.Node
	NodeFile = &Q.NodeFile
	StorageObject = &Q.StorageObject
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		BrowserFileMapping: newBrowserFileMapping(db, opts...),
		Library:            newLibrary(db, opts...),
		Node:               newNode(db, opts...),
		NodeFile:           newNodeFile(db, opts...),
		StorageObject:      newStorageObject(db, opts...),
		User:               newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	BrowserFileMapping browserFileMapping
	Library            library
	Node               node
	NodeFile           nodeFile
	StorageObject      storageObject
	User               user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		BrowserFileMapping: q.BrowserFileMapping.clone(db),
		Library:            q.Library.clone(db),
		Node:               q.Node.clone(db),
		NodeFile:           q.NodeFile.clone(db),
		StorageObject:      q.StorageObject.clone(db),
		User:               q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		BrowserFileMapping: q.BrowserFileMapping.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		Node:               q.Node.replaceDB(db),
		NodeFile:           q.NodeFile.replaceDB(db),
		StorageObject:      q.StorageObject.replaceDB(db),
		User:               q.User.replaceDB(db),
	}
}

type queryCtx struct {
	BrowserFileMapping IBrowserFileMappingDo
	Library            ILibraryDo
	Node               INodeDo
	NodeFile           INodeFileDo
	StorageObject      IStorageObjectDo
	User               IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		BrowserFileMapping: q.BrowserFileMapping.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		Node:               q.Node.WithContext(ctx),
		NodeFile:           q.NodeFile.WithContext(ctx),
		StorageObject:      q.StorageObject.WithContext(ctx),
		User:               q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
