// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                  = new(Query)
	BrowserBookmark    *browserBookmark
	BrowserFileMapping *browserFileMapping
	Library            *library
	Node               *node
	NodeFile           *nodeFile
	NodeResourceTarget *nodeResourceTarget
	NodeTagRel         *nodeTagRel
	StorageObject      *storageObject
	Tag                *tag
	TagAlias           *tagAlias
	TagBindPolicy      *tagBindPolicy
	TagTargetKind      *tagTargetKind
	UploadSession      *uploadSession
	User               *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	BrowserBookmark = &Q.BrowserBookmark
	BrowserFileMapping = &Q.BrowserFileMapping
	Library = &Q.Library
	Node = &Q.Node
	NodeFile = &Q.NodeFile
	NodeResourceTarget = &Q.NodeResourceTarget
	NodeTagRel = &Q.NodeTagRel
	StorageObject = &Q.StorageObject
	Tag = &Q.Tag
	TagAlias = &Q.TagAlias
	TagBindPolicy = &Q.TagBindPolicy
	TagTargetKind = &Q.TagTargetKind
	UploadSession = &Q.UploadSession
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                 db,
		BrowserBookmark:    newBrowserBookmark(db, opts...),
		BrowserFileMapping: newBrowserFileMapping(db, opts...),
		Library:            newLibrary(db, opts...),
		Node:               newNode(db, opts...),
		NodeFile:           newNodeFile(db, opts...),
		NodeResourceTarget: newNodeResourceTarget(db, opts...),
		NodeTagRel:         newNodeTagRel(db, opts...),
		StorageObject:      newStorageObject(db, opts...),
		Tag:                newTag(db, opts...),
		TagAlias:           newTagAlias(db, opts...),
		TagBindPolicy:      newTagBindPolicy(db, opts...),
		TagTargetKind:      newTagTargetKind(db, opts...),
		UploadSession:      newUploadSession(db, opts...),
		User:               newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	BrowserBookmark    browserBookmark
	BrowserFileMapping browserFileMapping
	Library            library
	Node               node
	NodeFile           nodeFile
	NodeResourceTarget nodeResourceTarget
	NodeTagRel         nodeTagRel
	StorageObject      storageObject
	Tag                tag
	TagAlias           tagAlias
	TagBindPolicy      tagBindPolicy
	TagTargetKind      tagTargetKind
	UploadSession      uploadSession
	User               user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		BrowserBookmark:    q.BrowserBookmark.clone(db),
		BrowserFileMapping: q.BrowserFileMapping.clone(db),
		Library:            q.Library.clone(db),
		Node:               q.Node.clone(db),
		NodeFile:           q.NodeFile.clone(db),
		NodeResourceTarget: q.NodeResourceTarget.clone(db),
		NodeTagRel:         q.NodeTagRel.clone(db),
		StorageObject:      q.StorageObject.clone(db),
		Tag:                q.Tag.clone(db),
		TagAlias:           q.TagAlias.clone(db),
		TagBindPolicy:      q.TagBindPolicy.clone(db),
		TagTargetKind:      q.TagTargetKind.clone(db),
		UploadSession:      q.UploadSession.clone(db),
		User:               q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                 db,
		BrowserBookmark:    q.BrowserBookmark.replaceDB(db),
		BrowserFileMapping: q.BrowserFileMapping.replaceDB(db),
		Library:            q.Library.replaceDB(db),
		Node:               q.Node.replaceDB(db),
		NodeFile:           q.NodeFile.replaceDB(db),
		NodeResourceTarget: q.NodeResourceTarget.replaceDB(db),
		NodeTagRel:         q.NodeTagRel.replaceDB(db),
		StorageObject:      q.StorageObject.replaceDB(db),
		Tag:                q.Tag.replaceDB(db),
		TagAlias:           q.TagAlias.replaceDB(db),
		TagBindPolicy:      q.TagBindPolicy.replaceDB(db),
		TagTargetKind:      q.TagTargetKind.replaceDB(db),
		UploadSession:      q.UploadSession.replaceDB(db),
		User:               q.User.replaceDB(db),
	}
}

type queryCtx struct {
	BrowserBookmark    IBrowserBookmarkDo
	BrowserFileMapping IBrowserFileMappingDo
	Library            ILibraryDo
	Node               INodeDo
	NodeFile           INodeFileDo
	NodeResourceTarget INodeResourceTargetDo
	NodeTagRel         INodeTagRelDo
	StorageObject      IStorageObjectDo
	Tag                ITagDo
	TagAlias           ITagAliasDo
	TagBindPolicy      ITagBindPolicyDo
	TagTargetKind      ITagTargetKindDo
	UploadSession      IUploadSessionDo
	User               IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		BrowserBookmark:    q.BrowserBookmark.WithContext(ctx),
		BrowserFileMapping: q.BrowserFileMapping.WithContext(ctx),
		Library:            q.Library.WithContext(ctx),
		Node:               q.Node.WithContext(ctx),
		NodeFile:           q.NodeFile.WithContext(ctx),
		NodeResourceTarget: q.NodeResourceTarget.WithContext(ctx),
		NodeTagRel:         q.NodeTagRel.WithContext(ctx),
		StorageObject:      q.StorageObject.WithContext(ctx),
		Tag:                q.Tag.WithContext(ctx),
		TagAlias:           q.TagAlias.WithContext(ctx),
		TagBindPolicy:      q.TagBindPolicy.WithContext(ctx),
		TagTargetKind:      q.TagTargetKind.WithContext(ctx),
		UploadSession:      q.UploadSession.WithContext(ctx),
		User:               q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
