// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newMigrationTaskItem(db *gorm.DB, opts ...gen.DOOption) migrationTaskItem {
	_migrationTaskItem := migrationTaskItem{}

	_migrationTaskItem.migrationTaskItemDo.UseDB(db, opts...)
	_migrationTaskItem.migrationTaskItemDo.UseModel(&model.MigrationTaskItem{})

	tableName := _migrationTaskItem.migrationTaskItemDo.TableName()
	_migrationTaskItem.ALL = field.NewAsterisk(tableName)
	_migrationTaskItem.ID = field.NewInt64(tableName, "id")
	_migrationTaskItem.TaskID = field.NewString(tableName, "task_id")
	_migrationTaskItem.StorageObjectID = field.NewInt64(tableName, "storage_object_id")
	_migrationTaskItem.SourceProvider = field.NewString(tableName, "source_provider")
	_migrationTaskItem.SourceBucket = field.NewString(tableName, "source_bucket")
	_migrationTaskItem.SourceKey = field.NewString(tableName, "source_key")
	_migrationTaskItem.TargetStorageObjectID = field.NewInt64(tableName, "target_storage_object_id")
	_migrationTaskItem.TargetKey = field.NewString(tableName, "target_key")
	_migrationTaskItem.FileSize = field.NewInt64(tableName, "file_size")
	_migrationTaskItem.Status = field.NewString(tableName, "status")
	_migrationTaskItem.ErrorMessage = field.NewString(tableName, "error_message")
	_migrationTaskItem.StartedAt = field.NewTime(tableName, "started_at")
	_migrationTaskItem.FinishedAt = field.NewTime(tableName, "finished_at")
	_migrationTaskItem.CreatedAt = field.NewTime(tableName, "created_at")

	_migrationTaskItem.fillFieldMap()

	return _migrationTaskItem
}

type migrationTaskItem struct {
	migrationTaskItemDo migrationTaskItemDo

	ALL                   field.Asterisk
	ID                    field.Int64
	TaskID                field.String
	StorageObjectID       field.Int64
	SourceProvider        field.String
	SourceBucket          field.String
	SourceKey             field.String
	TargetStorageObjectID field.Int64
	TargetKey             field.String
	FileSize              field.Int64
	Status                field.String
	ErrorMessage          field.String
	StartedAt             field.Time
	FinishedAt            field.Time
	CreatedAt             field.Time

	fieldMap map[string]field.Expr
}

func (m migrationTaskItem) Table(newTableName string) *migrationTaskItem {
	m.migrationTaskItemDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m migrationTaskItem) As(alias string) *migrationTaskItem {
	m.migrationTaskItemDo.DO = *(m.migrationTaskItemDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *migrationTaskItem) updateTableName(table string) *migrationTaskItem {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.TaskID = field.NewString(table, "task_id")
	m.StorageObjectID = field.NewInt64(table, "storage_object_id")
	m.SourceProvider = field.NewString(table, "source_provider")
	m.SourceBucket = field.NewString(table, "source_bucket")
	m.SourceKey = field.NewString(table, "source_key")
	m.TargetStorageObjectID = field.NewInt64(table, "target_storage_object_id")
	m.TargetKey = field.NewString(table, "target_key")
	m.FileSize = field.NewInt64(table, "file_size")
	m.Status = field.NewString(table, "status")
	m.ErrorMessage = field.NewString(table, "error_message")
	m.StartedAt = field.NewTime(table, "started_at")
	m.FinishedAt = field.NewTime(table, "finished_at")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *migrationTaskItem) WithContext(ctx context.Context) IMigrationTaskItemDo {
	return m.migrationTaskItemDo.WithContext(ctx)
}

func (m migrationTaskItem) TableName() string { return m.migrationTaskItemDo.TableName() }

func (m migrationTaskItem) Alias() string { return m.migrationTaskItemDo.Alias() }

func (m migrationTaskItem) Columns(cols ...field.Expr) gen.Columns {
	return m.migrationTaskItemDo.Columns(cols...)
}

func (m *migrationTaskItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *migrationTaskItem) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 14)
	m.fieldMap["id"] = m.ID
	m.fieldMap["task_id"] = m.TaskID
	m.fieldMap["storage_object_id"] = m.StorageObjectID
	m.fieldMap["source_provider"] = m.SourceProvider
	m.fieldMap["source_bucket"] = m.SourceBucket
	m.fieldMap["source_key"] = m.SourceKey
	m.fieldMap["target_storage_object_id"] = m.TargetStorageObjectID
	m.fieldMap["target_key"] = m.TargetKey
	m.fieldMap["file_size"] = m.FileSize
	m.fieldMap["status"] = m.Status
	m.fieldMap["error_message"] = m.ErrorMessage
	m.fieldMap["started_at"] = m.StartedAt
	m.fieldMap["finished_at"] = m.FinishedAt
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m migrationTaskItem) clone(db *gorm.DB) migrationTaskItem {
	m.migrationTaskItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m migrationTaskItem) replaceDB(db *gorm.DB) migrationTaskItem {
	m.migrationTaskItemDo.ReplaceDB(db)
	return m
}

type migrationTaskItemDo struct{ gen.DO }

type IMigrationTaskItemDo interface {
	gen.SubQuery
	Debug() IMigrationTaskItemDo
	WithContext(ctx context.Context) IMigrationTaskItemDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMigrationTaskItemDo
	WriteDB() IMigrationTaskItemDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMigrationTaskItemDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMigrationTaskItemDo
	Not(conds ...gen.Condition) IMigrationTaskItemDo
	Or(conds ...gen.Condition) IMigrationTaskItemDo
	Select(conds ...field.Expr) IMigrationTaskItemDo
	Where(conds ...gen.Condition) IMigrationTaskItemDo
	Order(conds ...field.Expr) IMigrationTaskItemDo
	Distinct(cols ...field.Expr) IMigrationTaskItemDo
	Omit(cols ...field.Expr) IMigrationTaskItemDo
	Join(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo
	Group(cols ...field.Expr) IMigrationTaskItemDo
	Having(conds ...gen.Condition) IMigrationTaskItemDo
	Limit(limit int) IMigrationTaskItemDo
	Offset(offset int) IMigrationTaskItemDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMigrationTaskItemDo
	Unscoped() IMigrationTaskItemDo
	Create(values ...*model.MigrationTaskItem) error
	CreateInBatches(values []*model.MigrationTaskItem, batchSize int) error
	Save(values ...*model.MigrationTaskItem) error
	First() (*model.MigrationTaskItem, error)
	Take() (*model.MigrationTaskItem, error)
	Last() (*model.MigrationTaskItem, error)
	Find() ([]*model.MigrationTaskItem, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MigrationTaskItem, err error)
	FindInBatches(result *[]*model.MigrationTaskItem, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MigrationTaskItem) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMigrationTaskItemDo
	Assign(attrs ...field.AssignExpr) IMigrationTaskItemDo
	Joins(fields ...field.RelationField) IMigrationTaskItemDo
	Preload(fields ...field.RelationField) IMigrationTaskItemDo
	FirstOrInit() (*model.MigrationTaskItem, error)
	FirstOrCreate() (*model.MigrationTaskItem, error)
	FindByPage(offset int, limit int) (result []*model.MigrationTaskItem, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMigrationTaskItemDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m migrationTaskItemDo) Debug() IMigrationTaskItemDo {
	return m.withDO(m.DO.Debug())
}

func (m migrationTaskItemDo) WithContext(ctx context.Context) IMigrationTaskItemDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m migrationTaskItemDo) ReadDB() IMigrationTaskItemDo {
	return m.Clauses(dbresolver.Read)
}

func (m migrationTaskItemDo) WriteDB() IMigrationTaskItemDo {
	return m.Clauses(dbresolver.Write)
}

func (m migrationTaskItemDo) Session(config *gorm.Session) IMigrationTaskItemDo {
	return m.withDO(m.DO.Session(config))
}

func (m migrationTaskItemDo) Clauses(conds ...clause.Expression) IMigrationTaskItemDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m migrationTaskItemDo) Returning(value interface{}, columns ...string) IMigrationTaskItemDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m migrationTaskItemDo) Not(conds ...gen.Condition) IMigrationTaskItemDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m migrationTaskItemDo) Or(conds ...gen.Condition) IMigrationTaskItemDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m migrationTaskItemDo) Select(conds ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m migrationTaskItemDo) Where(conds ...gen.Condition) IMigrationTaskItemDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m migrationTaskItemDo) Order(conds ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m migrationTaskItemDo) Distinct(cols ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m migrationTaskItemDo) Omit(cols ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m migrationTaskItemDo) Join(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m migrationTaskItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m migrationTaskItemDo) RightJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m migrationTaskItemDo) Group(cols ...field.Expr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m migrationTaskItemDo) Having(conds ...gen.Condition) IMigrationTaskItemDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m migrationTaskItemDo) Limit(limit int) IMigrationTaskItemDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m migrationTaskItemDo) Offset(offset int) IMigrationTaskItemDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m migrationTaskItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMigrationTaskItemDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m migrationTaskItemDo) Unscoped() IMigrationTaskItemDo {
	return m.withDO(m.DO.Unscoped())
}

func (m migrationTaskItemDo) Create(values ...*model.MigrationTaskItem) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m migrationTaskItemDo) CreateInBatches(values []*model.MigrationTaskItem, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m migrationTaskItemDo) Save(values ...*model.MigrationTaskItem) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m migrationTaskItemDo) First() (*model.MigrationTaskItem, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTaskItem), nil
	}
}

func (m migrationTaskItemDo) Take() (*model.MigrationTaskItem, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTaskItem), nil
	}
}

func (m migrationTaskItemDo) Last() (*model.MigrationTaskItem, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTaskItem), nil
	}
}

func (m migrationTaskItemDo) Find() ([]*model.MigrationTaskItem, error) {
	result, err := m.DO.Find()
	return result.([]*model.MigrationTaskItem), err
}

func (m migrationTaskItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MigrationTaskItem, err error) {
	buf := make([]*model.MigrationTaskItem, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m migrationTaskItemDo) FindInBatches(result *[]*model.MigrationTaskItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m migrationTaskItemDo) Attrs(attrs ...field.AssignExpr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m migrationTaskItemDo) Assign(attrs ...field.AssignExpr) IMigrationTaskItemDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m migrationTaskItemDo) Joins(fields ...field.RelationField) IMigrationTaskItemDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m migrationTaskItemDo) Preload(fields ...field.RelationField) IMigrationTaskItemDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m migrationTaskItemDo) FirstOrInit() (*model.MigrationTaskItem, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTaskItem), nil
	}
}

func (m migrationTaskItemDo) FirstOrCreate() (*model.MigrationTaskItem, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTaskItem), nil
	}
}

func (m migrationTaskItemDo) FindByPage(offset int, limit int) (result []*model.MigrationTaskItem, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m migrationTaskItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m migrationTaskItemDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m migrationTaskItemDo) Delete(models ...*model.MigrationTaskItem) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *migrationTaskItemDo) withDO(do gen.Dao) *migrationTaskItemDo {
	m.DO = *do.(*gen.DO)
	return m
}
