// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newMigrationTask(db *gorm.DB, opts ...gen.DOOption) migrationTask {
	_migrationTask := migrationTask{}

	_migrationTask.migrationTaskDo.UseDB(db, opts...)
	_migrationTask.migrationTaskDo.UseModel(&model.MigrationTask{})

	tableName := _migrationTask.migrationTaskDo.TableName()
	_migrationTask.ALL = field.NewAsterisk(tableName)
	_migrationTask.ID = field.NewString(tableName, "id")
	_migrationTask.ActorID = field.NewString(tableName, "actor_id")
	_migrationTask.LibraryID = field.NewInt64(tableName, "library_id")
	_migrationTask.RootNodeID = field.NewInt64(tableName, "root_node_id")
	_migrationTask.TargetProvider = field.NewString(tableName, "target_provider")
	_migrationTask.Status = field.NewString(tableName, "status")
	_migrationTask.TotalObjects = field.NewInt32(tableName, "total_objects")
	_migrationTask.CompletedObjects = field.NewInt32(tableName, "completed_objects")
	_migrationTask.FailedObjects = field.NewInt32(tableName, "failed_objects")
	_migrationTask.SkippedObjects = field.NewInt32(tableName, "skipped_objects")
	_migrationTask.TotalBytes = field.NewInt64(tableName, "total_bytes")
	_migrationTask.TransferredBytes = field.NewInt64(tableName, "transferred_bytes")
	_migrationTask.CurrentObjectKey = field.NewString(tableName, "current_object_key")
	_migrationTask.ErrorMessage = field.NewString(tableName, "error_message")
	_migrationTask.CreatedAt = field.NewTime(tableName, "created_at")
	_migrationTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_migrationTask.StartedAt = field.NewTime(tableName, "started_at")
	_migrationTask.FinishedAt = field.NewTime(tableName, "finished_at")

	_migrationTask.fillFieldMap()

	return _migrationTask
}

type migrationTask struct {
	migrationTaskDo migrationTaskDo

	ALL              field.Asterisk
	ID               field.String
	ActorID          field.String
	LibraryID        field.Int64
	RootNodeID       field.Int64
	TargetProvider   field.String
	Status           field.String
	TotalObjects     field.Int32
	CompletedObjects field.Int32
	FailedObjects    field.Int32
	SkippedObjects   field.Int32
	TotalBytes       field.Int64
	TransferredBytes field.Int64
	CurrentObjectKey field.String
	ErrorMessage     field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	StartedAt        field.Time
	FinishedAt       field.Time

	fieldMap map[string]field.Expr
}

func (m migrationTask) Table(newTableName string) *migrationTask {
	m.migrationTaskDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m migrationTask) As(alias string) *migrationTask {
	m.migrationTaskDo.DO = *(m.migrationTaskDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *migrationTask) updateTableName(table string) *migrationTask {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewString(table, "id")
	m.ActorID = field.NewString(table, "actor_id")
	m.LibraryID = field.NewInt64(table, "library_id")
	m.RootNodeID = field.NewInt64(table, "root_node_id")
	m.TargetProvider = field.NewString(table, "target_provider")
	m.Status = field.NewString(table, "status")
	m.TotalObjects = field.NewInt32(table, "total_objects")
	m.CompletedObjects = field.NewInt32(table, "completed_objects")
	m.FailedObjects = field.NewInt32(table, "failed_objects")
	m.SkippedObjects = field.NewInt32(table, "skipped_objects")
	m.TotalBytes = field.NewInt64(table, "total_bytes")
	m.TransferredBytes = field.NewInt64(table, "transferred_bytes")
	m.CurrentObjectKey = field.NewString(table, "current_object_key")
	m.ErrorMessage = field.NewString(table, "error_message")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.StartedAt = field.NewTime(table, "started_at")
	m.FinishedAt = field.NewTime(table, "finished_at")

	m.fillFieldMap()

	return m
}

func (m *migrationTask) WithContext(ctx context.Context) IMigrationTaskDo {
	return m.migrationTaskDo.WithContext(ctx)
}

func (m migrationTask) TableName() string { return m.migrationTaskDo.TableName() }

func (m migrationTask) Alias() string { return m.migrationTaskDo.Alias() }

func (m migrationTask) Columns(cols ...field.Expr) gen.Columns {
	return m.migrationTaskDo.Columns(cols...)
}

func (m *migrationTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *migrationTask) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 18)
	m.fieldMap["id"] = m.ID
	m.fieldMap["actor_id"] = m.ActorID
	m.fieldMap["library_id"] = m.LibraryID
	m.fieldMap["root_node_id"] = m.RootNodeID
	m.fieldMap["target_provider"] = m.TargetProvider
	m.fieldMap["status"] = m.Status
	m.fieldMap["total_objects"] = m.TotalObjects
	m.fieldMap["completed_objects"] = m.CompletedObjects
	m.fieldMap["failed_objects"] = m.FailedObjects
	m.fieldMap["skipped_objects"] = m.SkippedObjects
	m.fieldMap["total_bytes"] = m.TotalBytes
	m.fieldMap["transferred_bytes"] = m.TransferredBytes
	m.fieldMap["current_object_key"] = m.CurrentObjectKey
	m.fieldMap["error_message"] = m.ErrorMessage
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["started_at"] = m.StartedAt
	m.fieldMap["finished_at"] = m.FinishedAt
}

func (m migrationTask) clone(db *gorm.DB) migrationTask {
	m.migrationTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m migrationTask) replaceDB(db *gorm.DB) migrationTask {
	m.migrationTaskDo.ReplaceDB(db)
	return m
}

type migrationTaskDo struct{ gen.DO }

type IMigrationTaskDo interface {
	gen.SubQuery
	Debug() IMigrationTaskDo
	WithContext(ctx context.Context) IMigrationTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMigrationTaskDo
	WriteDB() IMigrationTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMigrationTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMigrationTaskDo
	Not(conds ...gen.Condition) IMigrationTaskDo
	Or(conds ...gen.Condition) IMigrationTaskDo
	Select(conds ...field.Expr) IMigrationTaskDo
	Where(conds ...gen.Condition) IMigrationTaskDo
	Order(conds ...field.Expr) IMigrationTaskDo
	Distinct(cols ...field.Expr) IMigrationTaskDo
	Omit(cols ...field.Expr) IMigrationTaskDo
	Join(table schema.Tabler, on ...field.Expr) IMigrationTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskDo
	Group(cols ...field.Expr) IMigrationTaskDo
	Having(conds ...gen.Condition) IMigrationTaskDo
	Limit(limit int) IMigrationTaskDo
	Offset(offset int) IMigrationTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMigrationTaskDo
	Unscoped() IMigrationTaskDo
	Create(values ...*model.MigrationTask) error
	CreateInBatches(values []*model.MigrationTask, batchSize int) error
	Save(values ...*model.MigrationTask) error
	First() (*model.MigrationTask, error)
	Take() (*model.MigrationTask, error)
	Last() (*model.MigrationTask, error)
	Find() ([]*model.MigrationTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MigrationTask, err error)
	FindInBatches(result *[]*model.MigrationTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MigrationTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMigrationTaskDo
	Assign(attrs ...field.AssignExpr) IMigrationTaskDo
	Joins(fields ...field.RelationField) IMigrationTaskDo
	Preload(fields ...field.RelationField) IMigrationTaskDo
	FirstOrInit() (*model.MigrationTask, error)
	FirstOrCreate() (*model.MigrationTask, error)
	FindByPage(offset int, limit int) (result []*model.MigrationTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMigrationTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m migrationTaskDo) Debug() IMigrationTaskDo {
	return m.withDO(m.DO.Debug())
}

func (m migrationTaskDo) WithContext(ctx context.Context) IMigrationTaskDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m migrationTaskDo) ReadDB() IMigrationTaskDo {
	return m.Clauses(dbresolver.Read)
}

func (m migrationTaskDo) WriteDB() IMigrationTaskDo {
	return m.Clauses(dbresolver.Write)
}

func (m migrationTaskDo) Session(config *gorm.Session) IMigrationTaskDo {
	return m.withDO(m.DO.Session(config))
}

func (m migrationTaskDo) Clauses(conds ...clause.Expression) IMigrationTaskDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m migrationTaskDo) Returning(value interface{}, columns ...string) IMigrationTaskDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m migrationTaskDo) Not(conds ...gen.Condition) IMigrationTaskDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m migrationTaskDo) Or(conds ...gen.Condition) IMigrationTaskDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m migrationTaskDo) Select(conds ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m migrationTaskDo) Where(conds ...gen.Condition) IMigrationTaskDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m migrationTaskDo) Order(conds ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m migrationTaskDo) Distinct(cols ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m migrationTaskDo) Omit(cols ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m migrationTaskDo) Join(table schema.Tabler, on ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m migrationTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m migrationTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m migrationTaskDo) Group(cols ...field.Expr) IMigrationTaskDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m migrationTaskDo) Having(conds ...gen.Condition) IMigrationTaskDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m migrationTaskDo) Limit(limit int) IMigrationTaskDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m migrationTaskDo) Offset(offset int) IMigrationTaskDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m migrationTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMigrationTaskDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m migrationTaskDo) Unscoped() IMigrationTaskDo {
	return m.withDO(m.DO.Unscoped())
}

func (m migrationTaskDo) Create(values ...*model.MigrationTask) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m migrationTaskDo) CreateInBatches(values []*model.MigrationTask, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m migrationTaskDo) Save(values ...*model.MigrationTask) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m migrationTaskDo) First() (*model.MigrationTask, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTask), nil
	}
}

func (m migrationTaskDo) Take() (*model.MigrationTask, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTask), nil
	}
}

func (m migrationTaskDo) Last() (*model.MigrationTask, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTask), nil
	}
}

func (m migrationTaskDo) Find() ([]*model.MigrationTask, error) {
	result, err := m.DO.Find()
	return result.([]*model.MigrationTask), err
}

func (m migrationTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MigrationTask, err error) {
	buf := make([]*model.MigrationTask, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m migrationTaskDo) FindInBatches(result *[]*model.MigrationTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m migrationTaskDo) Attrs(attrs ...field.AssignExpr) IMigrationTaskDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m migrationTaskDo) Assign(attrs ...field.AssignExpr) IMigrationTaskDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m migrationTaskDo) Joins(fields ...field.RelationField) IMigrationTaskDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m migrationTaskDo) Preload(fields ...field.RelationField) IMigrationTaskDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m migrationTaskDo) FirstOrInit() (*model.MigrationTask, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTask), nil
	}
}

func (m migrationTaskDo) FirstOrCreate() (*model.MigrationTask, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MigrationTask), nil
	}
}

func (m migrationTaskDo) FindByPage(offset int, limit int) (result []*model.MigrationTask, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m migrationTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m migrationTaskDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m migrationTaskDo) Delete(models ...*model.MigrationTask) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *migrationTaskDo) withDO(do gen.Dao) *migrationTaskDo {
	m.DO = *do.(*gen.DO)
	return m
}
