// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newNodeTagRel(db *gorm.DB, opts ...gen.DOOption) nodeTagRel {
	_nodeTagRel := nodeTagRel{}

	_nodeTagRel.nodeTagRelDo.UseDB(db, opts...)
	_nodeTagRel.nodeTagRelDo.UseModel(&model.NodeTagRel{})

	tableName := _nodeTagRel.nodeTagRelDo.TableName()
	_nodeTagRel.ALL = field.NewAsterisk(tableName)
	_nodeTagRel.ID = field.NewInt64(tableName, "id")
	_nodeTagRel.NodeID = field.NewInt64(tableName, "node_id")
	_nodeTagRel.TagID = field.NewInt64(tableName, "tag_id")
	_nodeTagRel.LibraryID = field.NewInt64(tableName, "library_id")
	_nodeTagRel.CreatedAt = field.NewTime(tableName, "created_at")

	_nodeTagRel.fillFieldMap()

	return _nodeTagRel
}

type nodeTagRel struct {
	nodeTagRelDo nodeTagRelDo

	ALL       field.Asterisk
	ID        field.Int64
	NodeID    field.Int64
	TagID     field.Int64
	LibraryID field.Int64
	CreatedAt field.Time

	fieldMap map[string]field.Expr
}

func (n nodeTagRel) Table(newTableName string) *nodeTagRel {
	n.nodeTagRelDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeTagRel) As(alias string) *nodeTagRel {
	n.nodeTagRelDo.DO = *(n.nodeTagRelDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeTagRel) updateTableName(table string) *nodeTagRel {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.NodeID = field.NewInt64(table, "node_id")
	n.TagID = field.NewInt64(table, "tag_id")
	n.LibraryID = field.NewInt64(table, "library_id")
	n.CreatedAt = field.NewTime(table, "created_at")

	n.fillFieldMap()

	return n
}

func (n *nodeTagRel) WithContext(ctx context.Context) INodeTagRelDo {
	return n.nodeTagRelDo.WithContext(ctx)
}

func (n nodeTagRel) TableName() string { return n.nodeTagRelDo.TableName() }

func (n nodeTagRel) Alias() string { return n.nodeTagRelDo.Alias() }

func (n nodeTagRel) Columns(cols ...field.Expr) gen.Columns { return n.nodeTagRelDo.Columns(cols...) }

func (n *nodeTagRel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeTagRel) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 5)
	n.fieldMap["id"] = n.ID
	n.fieldMap["node_id"] = n.NodeID
	n.fieldMap["tag_id"] = n.TagID
	n.fieldMap["library_id"] = n.LibraryID
	n.fieldMap["created_at"] = n.CreatedAt
}

func (n nodeTagRel) clone(db *gorm.DB) nodeTagRel {
	n.nodeTagRelDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeTagRel) replaceDB(db *gorm.DB) nodeTagRel {
	n.nodeTagRelDo.ReplaceDB(db)
	return n
}

type nodeTagRelDo struct{ gen.DO }

type INodeTagRelDo interface {
	gen.SubQuery
	Debug() INodeTagRelDo
	WithContext(ctx context.Context) INodeTagRelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeTagRelDo
	WriteDB() INodeTagRelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeTagRelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeTagRelDo
	Not(conds ...gen.Condition) INodeTagRelDo
	Or(conds ...gen.Condition) INodeTagRelDo
	Select(conds ...field.Expr) INodeTagRelDo
	Where(conds ...gen.Condition) INodeTagRelDo
	Order(conds ...field.Expr) INodeTagRelDo
	Distinct(cols ...field.Expr) INodeTagRelDo
	Omit(cols ...field.Expr) INodeTagRelDo
	Join(table schema.Tabler, on ...field.Expr) INodeTagRelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeTagRelDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeTagRelDo
	Group(cols ...field.Expr) INodeTagRelDo
	Having(conds ...gen.Condition) INodeTagRelDo
	Limit(limit int) INodeTagRelDo
	Offset(offset int) INodeTagRelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeTagRelDo
	Unscoped() INodeTagRelDo
	Create(values ...*model.NodeTagRel) error
	CreateInBatches(values []*model.NodeTagRel, batchSize int) error
	Save(values ...*model.NodeTagRel) error
	First() (*model.NodeTagRel, error)
	Take() (*model.NodeTagRel, error)
	Last() (*model.NodeTagRel, error)
	Find() ([]*model.NodeTagRel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeTagRel, err error)
	FindInBatches(result *[]*model.NodeTagRel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeTagRel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeTagRelDo
	Assign(attrs ...field.AssignExpr) INodeTagRelDo
	Joins(fields ...field.RelationField) INodeTagRelDo
	Preload(fields ...field.RelationField) INodeTagRelDo
	FirstOrInit() (*model.NodeTagRel, error)
	FirstOrCreate() (*model.NodeTagRel, error)
	FindByPage(offset int, limit int) (result []*model.NodeTagRel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeTagRelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeTagRelDo) Debug() INodeTagRelDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeTagRelDo) WithContext(ctx context.Context) INodeTagRelDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeTagRelDo) ReadDB() INodeTagRelDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeTagRelDo) WriteDB() INodeTagRelDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeTagRelDo) Session(config *gorm.Session) INodeTagRelDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeTagRelDo) Clauses(conds ...clause.Expression) INodeTagRelDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeTagRelDo) Returning(value interface{}, columns ...string) INodeTagRelDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeTagRelDo) Not(conds ...gen.Condition) INodeTagRelDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeTagRelDo) Or(conds ...gen.Condition) INodeTagRelDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeTagRelDo) Select(conds ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeTagRelDo) Where(conds ...gen.Condition) INodeTagRelDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeTagRelDo) Order(conds ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeTagRelDo) Distinct(cols ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeTagRelDo) Omit(cols ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeTagRelDo) Join(table schema.Tabler, on ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeTagRelDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeTagRelDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeTagRelDo) Group(cols ...field.Expr) INodeTagRelDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeTagRelDo) Having(conds ...gen.Condition) INodeTagRelDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeTagRelDo) Limit(limit int) INodeTagRelDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeTagRelDo) Offset(offset int) INodeTagRelDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeTagRelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeTagRelDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeTagRelDo) Unscoped() INodeTagRelDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeTagRelDo) Create(values ...*model.NodeTagRel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeTagRelDo) CreateInBatches(values []*model.NodeTagRel, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeTagRelDo) Save(values ...*model.NodeTagRel) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeTagRelDo) First() (*model.NodeTagRel, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeTagRel), nil
	}
}

func (n nodeTagRelDo) Take() (*model.NodeTagRel, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeTagRel), nil
	}
}

func (n nodeTagRelDo) Last() (*model.NodeTagRel, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeTagRel), nil
	}
}

func (n nodeTagRelDo) Find() ([]*model.NodeTagRel, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeTagRel), err
}

func (n nodeTagRelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeTagRel, err error) {
	buf := make([]*model.NodeTagRel, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeTagRelDo) FindInBatches(result *[]*model.NodeTagRel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeTagRelDo) Attrs(attrs ...field.AssignExpr) INodeTagRelDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeTagRelDo) Assign(attrs ...field.AssignExpr) INodeTagRelDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeTagRelDo) Joins(fields ...field.RelationField) INodeTagRelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeTagRelDo) Preload(fields ...field.RelationField) INodeTagRelDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeTagRelDo) FirstOrInit() (*model.NodeTagRel, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeTagRel), nil
	}
}

func (n nodeTagRelDo) FirstOrCreate() (*model.NodeTagRel, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeTagRel), nil
	}
}

func (n nodeTagRelDo) FindByPage(offset int, limit int) (result []*model.NodeTagRel, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeTagRelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeTagRelDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeTagRelDo) Delete(models ...*model.NodeTagRel) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeTagRelDo) withDO(do gen.Dao) *nodeTagRelDo {
	n.DO = *do.(*gen.DO)
	return n
}
