// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newNode(db *gorm.DB, opts ...gen.DOOption) node {
	_node := node{}

	_node.nodeDo.UseDB(db, opts...)
	_node.nodeDo.UseModel(&model.Node{})

	tableName := _node.nodeDo.TableName()
	_node.ALL = field.NewAsterisk(tableName)
	_node.ID = field.NewInt64(tableName, "id")
	_node.LibraryID = field.NewInt64(tableName, "library_id")
	_node.ParentID = field.NewInt64(tableName, "parent_id")
	_node.NodeType = field.NewInt16(tableName, "node_type")
	_node.Name = field.NewString(tableName, "name")
	_node.Ext = field.NewString(tableName, "ext")
	_node.BuiltInType = field.NewString(tableName, "built_in_type")
	_node.ArchiveMode = field.NewBool(tableName, "archive_mode")
	_node.ViewMeta = field.NewString(tableName, "view_meta")
	_node.SortOrder = field.NewInt32(tableName, "sort_order")
	_node.DeletedAt = field.NewField(tableName, "deleted_at")
	_node.CreatedAt = field.NewTime(tableName, "created_at")
	_node.UpdatedAt = field.NewTime(tableName, "updated_at")

	_node.fillFieldMap()

	return _node
}

type node struct {
	nodeDo nodeDo

	ALL         field.Asterisk
	ID          field.Int64
	LibraryID   field.Int64
	ParentID    field.Int64
	NodeType    field.Int16  // 0=folder, 1=file
	Name        field.String // 文件时不含后缀名；文件夹时为目录名
	Ext         field.String // 仅文件使用，建议不带点，例如 jpg / zip / go
	BuiltInType field.String // 开放字符串，当前核心值 DEF/COMIC/ASMR；写入前统一转大写
	ArchiveMode field.Bool   // 当前主要用于目录浏览入口切换；数据库层不强制仅目录可开
	ViewMeta    field.String // 可扩展视图配置 JSONB；当前稳定关键键包括 tagIds
	SortOrder   field.Int32
	DeletedAt   field.Field
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (n node) Table(newTableName string) *node {
	n.nodeDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n node) As(alias string) *node {
	n.nodeDo.DO = *(n.nodeDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *node) updateTableName(table string) *node {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.LibraryID = field.NewInt64(table, "library_id")
	n.ParentID = field.NewInt64(table, "parent_id")
	n.NodeType = field.NewInt16(table, "node_type")
	n.Name = field.NewString(table, "name")
	n.Ext = field.NewString(table, "ext")
	n.BuiltInType = field.NewString(table, "built_in_type")
	n.ArchiveMode = field.NewBool(table, "archive_mode")
	n.ViewMeta = field.NewString(table, "view_meta")
	n.SortOrder = field.NewInt32(table, "sort_order")
	n.DeletedAt = field.NewField(table, "deleted_at")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *node) WithContext(ctx context.Context) INodeDo { return n.nodeDo.WithContext(ctx) }

func (n node) TableName() string { return n.nodeDo.TableName() }

func (n node) Alias() string { return n.nodeDo.Alias() }

func (n node) Columns(cols ...field.Expr) gen.Columns { return n.nodeDo.Columns(cols...) }

func (n *node) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *node) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["library_id"] = n.LibraryID
	n.fieldMap["parent_id"] = n.ParentID
	n.fieldMap["node_type"] = n.NodeType
	n.fieldMap["name"] = n.Name
	n.fieldMap["ext"] = n.Ext
	n.fieldMap["built_in_type"] = n.BuiltInType
	n.fieldMap["archive_mode"] = n.ArchiveMode
	n.fieldMap["view_meta"] = n.ViewMeta
	n.fieldMap["sort_order"] = n.SortOrder
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n node) clone(db *gorm.DB) node {
	n.nodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n node) replaceDB(db *gorm.DB) node {
	n.nodeDo.ReplaceDB(db)
	return n
}

type nodeDo struct{ gen.DO }

type INodeDo interface {
	gen.SubQuery
	Debug() INodeDo
	WithContext(ctx context.Context) INodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeDo
	WriteDB() INodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeDo
	Not(conds ...gen.Condition) INodeDo
	Or(conds ...gen.Condition) INodeDo
	Select(conds ...field.Expr) INodeDo
	Where(conds ...gen.Condition) INodeDo
	Order(conds ...field.Expr) INodeDo
	Distinct(cols ...field.Expr) INodeDo
	Omit(cols ...field.Expr) INodeDo
	Join(table schema.Tabler, on ...field.Expr) INodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeDo
	Group(cols ...field.Expr) INodeDo
	Having(conds ...gen.Condition) INodeDo
	Limit(limit int) INodeDo
	Offset(offset int) INodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeDo
	Unscoped() INodeDo
	Create(values ...*model.Node) error
	CreateInBatches(values []*model.Node, batchSize int) error
	Save(values ...*model.Node) error
	First() (*model.Node, error)
	Take() (*model.Node, error)
	Last() (*model.Node, error)
	Find() ([]*model.Node, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Node, err error)
	FindInBatches(result *[]*model.Node, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Node) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeDo
	Assign(attrs ...field.AssignExpr) INodeDo
	Joins(fields ...field.RelationField) INodeDo
	Preload(fields ...field.RelationField) INodeDo
	FirstOrInit() (*model.Node, error)
	FirstOrCreate() (*model.Node, error)
	FindByPage(offset int, limit int) (result []*model.Node, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeDo) Debug() INodeDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeDo) WithContext(ctx context.Context) INodeDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeDo) ReadDB() INodeDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeDo) WriteDB() INodeDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeDo) Session(config *gorm.Session) INodeDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeDo) Clauses(conds ...clause.Expression) INodeDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeDo) Returning(value interface{}, columns ...string) INodeDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeDo) Not(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeDo) Or(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeDo) Select(conds ...field.Expr) INodeDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeDo) Where(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeDo) Order(conds ...field.Expr) INodeDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeDo) Distinct(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeDo) Omit(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeDo) Join(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeDo) Group(cols ...field.Expr) INodeDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeDo) Having(conds ...gen.Condition) INodeDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeDo) Limit(limit int) INodeDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeDo) Offset(offset int) INodeDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeDo) Unscoped() INodeDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeDo) Create(values ...*model.Node) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeDo) CreateInBatches(values []*model.Node, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeDo) Save(values ...*model.Node) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeDo) First() (*model.Node, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Node), nil
	}
}

func (n nodeDo) Take() (*model.Node, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Node), nil
	}
}

func (n nodeDo) Last() (*model.Node, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Node), nil
	}
}

func (n nodeDo) Find() ([]*model.Node, error) {
	result, err := n.DO.Find()
	return result.([]*model.Node), err
}

func (n nodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Node, err error) {
	buf := make([]*model.Node, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeDo) FindInBatches(result *[]*model.Node, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeDo) Attrs(attrs ...field.AssignExpr) INodeDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeDo) Assign(attrs ...field.AssignExpr) INodeDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeDo) Joins(fields ...field.RelationField) INodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeDo) Preload(fields ...field.RelationField) INodeDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeDo) FirstOrInit() (*model.Node, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Node), nil
	}
}

func (n nodeDo) FirstOrCreate() (*model.Node, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Node), nil
	}
}

func (n nodeDo) FindByPage(offset int, limit int) (result []*model.Node, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeDo) Delete(models ...*model.Node) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeDo) withDO(do gen.Dao) *nodeDo {
	n.DO = *do.(*gen.DO)
	return n
}
