// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newNodeFile(db *gorm.DB, opts ...gen.DOOption) nodeFile {
	_nodeFile := nodeFile{}

	_nodeFile.nodeFileDo.UseDB(db, opts...)
	_nodeFile.nodeFileDo.UseModel(&model.NodeFile{})

	tableName := _nodeFile.nodeFileDo.TableName()
	_nodeFile.ALL = field.NewAsterisk(tableName)
	_nodeFile.FileID = field.NewInt64(tableName, "file_id")
	_nodeFile.LibraryID = field.NewInt64(tableName, "library_id")
	_nodeFile.StorageObjectID = field.NewInt64(tableName, "storage_object_id")
	_nodeFile.MimeType = field.NewString(tableName, "mime_type")
	_nodeFile.FileSize = field.NewInt64(tableName, "file_size")
	_nodeFile.ChecksumSha256 = field.NewString(tableName, "checksum_sha256")
	_nodeFile.CreatedAt = field.NewTime(tableName, "created_at")
	_nodeFile.UpdatedAt = field.NewTime(tableName, "updated_at")

	_nodeFile.fillFieldMap()

	return _nodeFile
}

type nodeFile struct {
	nodeFileDo nodeFileDo

	ALL             field.Asterisk
	FileID          field.Int64
	LibraryID       field.Int64
	StorageObjectID field.Int64
	MimeType        field.String // 前端直接依赖：文件类型判断、预览分发、属性展示
	FileSize        field.Int64  // 前端直接依赖：属性展示、列表/回收站展示
	ChecksumSha256  field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (n nodeFile) Table(newTableName string) *nodeFile {
	n.nodeFileDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeFile) As(alias string) *nodeFile {
	n.nodeFileDo.DO = *(n.nodeFileDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeFile) updateTableName(table string) *nodeFile {
	n.ALL = field.NewAsterisk(table)
	n.FileID = field.NewInt64(table, "file_id")
	n.LibraryID = field.NewInt64(table, "library_id")
	n.StorageObjectID = field.NewInt64(table, "storage_object_id")
	n.MimeType = field.NewString(table, "mime_type")
	n.FileSize = field.NewInt64(table, "file_size")
	n.ChecksumSha256 = field.NewString(table, "checksum_sha256")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *nodeFile) WithContext(ctx context.Context) INodeFileDo { return n.nodeFileDo.WithContext(ctx) }

func (n nodeFile) TableName() string { return n.nodeFileDo.TableName() }

func (n nodeFile) Alias() string { return n.nodeFileDo.Alias() }

func (n nodeFile) Columns(cols ...field.Expr) gen.Columns { return n.nodeFileDo.Columns(cols...) }

func (n *nodeFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeFile) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 8)
	n.fieldMap["file_id"] = n.FileID
	n.fieldMap["library_id"] = n.LibraryID
	n.fieldMap["storage_object_id"] = n.StorageObjectID
	n.fieldMap["mime_type"] = n.MimeType
	n.fieldMap["file_size"] = n.FileSize
	n.fieldMap["checksum_sha256"] = n.ChecksumSha256
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n nodeFile) clone(db *gorm.DB) nodeFile {
	n.nodeFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeFile) replaceDB(db *gorm.DB) nodeFile {
	n.nodeFileDo.ReplaceDB(db)
	return n
}

type nodeFileDo struct{ gen.DO }

type INodeFileDo interface {
	gen.SubQuery
	Debug() INodeFileDo
	WithContext(ctx context.Context) INodeFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeFileDo
	WriteDB() INodeFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeFileDo
	Not(conds ...gen.Condition) INodeFileDo
	Or(conds ...gen.Condition) INodeFileDo
	Select(conds ...field.Expr) INodeFileDo
	Where(conds ...gen.Condition) INodeFileDo
	Order(conds ...field.Expr) INodeFileDo
	Distinct(cols ...field.Expr) INodeFileDo
	Omit(cols ...field.Expr) INodeFileDo
	Join(table schema.Tabler, on ...field.Expr) INodeFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeFileDo
	Group(cols ...field.Expr) INodeFileDo
	Having(conds ...gen.Condition) INodeFileDo
	Limit(limit int) INodeFileDo
	Offset(offset int) INodeFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeFileDo
	Unscoped() INodeFileDo
	Create(values ...*model.NodeFile) error
	CreateInBatches(values []*model.NodeFile, batchSize int) error
	Save(values ...*model.NodeFile) error
	First() (*model.NodeFile, error)
	Take() (*model.NodeFile, error)
	Last() (*model.NodeFile, error)
	Find() ([]*model.NodeFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeFile, err error)
	FindInBatches(result *[]*model.NodeFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeFileDo
	Assign(attrs ...field.AssignExpr) INodeFileDo
	Joins(fields ...field.RelationField) INodeFileDo
	Preload(fields ...field.RelationField) INodeFileDo
	FirstOrInit() (*model.NodeFile, error)
	FirstOrCreate() (*model.NodeFile, error)
	FindByPage(offset int, limit int) (result []*model.NodeFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeFileDo) Debug() INodeFileDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeFileDo) WithContext(ctx context.Context) INodeFileDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeFileDo) ReadDB() INodeFileDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeFileDo) WriteDB() INodeFileDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeFileDo) Session(config *gorm.Session) INodeFileDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeFileDo) Clauses(conds ...clause.Expression) INodeFileDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeFileDo) Returning(value interface{}, columns ...string) INodeFileDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeFileDo) Not(conds ...gen.Condition) INodeFileDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeFileDo) Or(conds ...gen.Condition) INodeFileDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeFileDo) Select(conds ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeFileDo) Where(conds ...gen.Condition) INodeFileDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeFileDo) Order(conds ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeFileDo) Distinct(cols ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeFileDo) Omit(cols ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeFileDo) Join(table schema.Tabler, on ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeFileDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeFileDo) Group(cols ...field.Expr) INodeFileDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeFileDo) Having(conds ...gen.Condition) INodeFileDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeFileDo) Limit(limit int) INodeFileDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeFileDo) Offset(offset int) INodeFileDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeFileDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeFileDo) Unscoped() INodeFileDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeFileDo) Create(values ...*model.NodeFile) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeFileDo) CreateInBatches(values []*model.NodeFile, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeFileDo) Save(values ...*model.NodeFile) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeFileDo) First() (*model.NodeFile, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeFile), nil
	}
}

func (n nodeFileDo) Take() (*model.NodeFile, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeFile), nil
	}
}

func (n nodeFileDo) Last() (*model.NodeFile, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeFile), nil
	}
}

func (n nodeFileDo) Find() ([]*model.NodeFile, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeFile), err
}

func (n nodeFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeFile, err error) {
	buf := make([]*model.NodeFile, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeFileDo) FindInBatches(result *[]*model.NodeFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeFileDo) Attrs(attrs ...field.AssignExpr) INodeFileDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeFileDo) Assign(attrs ...field.AssignExpr) INodeFileDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeFileDo) Joins(fields ...field.RelationField) INodeFileDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeFileDo) Preload(fields ...field.RelationField) INodeFileDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeFileDo) FirstOrInit() (*model.NodeFile, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeFile), nil
	}
}

func (n nodeFileDo) FirstOrCreate() (*model.NodeFile, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeFile), nil
	}
}

func (n nodeFileDo) FindByPage(offset int, limit int) (result []*model.NodeFile, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeFileDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeFileDo) Delete(models ...*model.NodeFile) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeFileDo) withDO(do gen.Dao) *nodeFileDo {
	n.DO = *do.(*gen.DO)
	return n
}
