// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newNodeMutationReceipt(db *gorm.DB, opts ...gen.DOOption) nodeMutationReceipt {
	_nodeMutationReceipt := nodeMutationReceipt{}

	_nodeMutationReceipt.nodeMutationReceiptDo.UseDB(db, opts...)
	_nodeMutationReceipt.nodeMutationReceiptDo.UseModel(&model.NodeMutationReceipt{})

	tableName := _nodeMutationReceipt.nodeMutationReceiptDo.TableName()
	_nodeMutationReceipt.ALL = field.NewAsterisk(tableName)
	_nodeMutationReceipt.ActorID = field.NewString(tableName, "actor_id")
	_nodeMutationReceipt.OperationID = field.NewString(tableName, "operation_id")
	_nodeMutationReceipt.LibraryID = field.NewInt64(tableName, "library_id")
	_nodeMutationReceipt.Kind = field.NewString(tableName, "kind")
	_nodeMutationReceipt.RequestHash = field.NewString(tableName, "request_hash")
	_nodeMutationReceipt.Result = field.NewString(tableName, "result")
	_nodeMutationReceipt.CommittedAt = field.NewTime(tableName, "committed_at")

	_nodeMutationReceipt.fillFieldMap()

	return _nodeMutationReceipt
}

type nodeMutationReceipt struct {
	nodeMutationReceiptDo nodeMutationReceiptDo

	ALL         field.Asterisk
	ActorID     field.String
	OperationID field.String
	LibraryID   field.Int64
	Kind        field.String
	RequestHash field.String
	Result      field.String
	CommittedAt field.Time

	fieldMap map[string]field.Expr
}

func (n nodeMutationReceipt) Table(newTableName string) *nodeMutationReceipt {
	n.nodeMutationReceiptDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeMutationReceipt) As(alias string) *nodeMutationReceipt {
	n.nodeMutationReceiptDo.DO = *(n.nodeMutationReceiptDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeMutationReceipt) updateTableName(table string) *nodeMutationReceipt {
	n.ALL = field.NewAsterisk(table)
	n.ActorID = field.NewString(table, "actor_id")
	n.OperationID = field.NewString(table, "operation_id")
	n.LibraryID = field.NewInt64(table, "library_id")
	n.Kind = field.NewString(table, "kind")
	n.RequestHash = field.NewString(table, "request_hash")
	n.Result = field.NewString(table, "result")
	n.CommittedAt = field.NewTime(table, "committed_at")

	n.fillFieldMap()

	return n
}

func (n *nodeMutationReceipt) WithContext(ctx context.Context) INodeMutationReceiptDo {
	return n.nodeMutationReceiptDo.WithContext(ctx)
}

func (n nodeMutationReceipt) TableName() string { return n.nodeMutationReceiptDo.TableName() }

func (n nodeMutationReceipt) Alias() string { return n.nodeMutationReceiptDo.Alias() }

func (n nodeMutationReceipt) Columns(cols ...field.Expr) gen.Columns {
	return n.nodeMutationReceiptDo.Columns(cols...)
}

func (n *nodeMutationReceipt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeMutationReceipt) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 7)
	n.fieldMap["actor_id"] = n.ActorID
	n.fieldMap["operation_id"] = n.OperationID
	n.fieldMap["library_id"] = n.LibraryID
	n.fieldMap["kind"] = n.Kind
	n.fieldMap["request_hash"] = n.RequestHash
	n.fieldMap["result"] = n.Result
	n.fieldMap["committed_at"] = n.CommittedAt
}

func (n nodeMutationReceipt) clone(db *gorm.DB) nodeMutationReceipt {
	n.nodeMutationReceiptDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeMutationReceipt) replaceDB(db *gorm.DB) nodeMutationReceipt {
	n.nodeMutationReceiptDo.ReplaceDB(db)
	return n
}

type nodeMutationReceiptDo struct{ gen.DO }

type INodeMutationReceiptDo interface {
	gen.SubQuery
	Debug() INodeMutationReceiptDo
	WithContext(ctx context.Context) INodeMutationReceiptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeMutationReceiptDo
	WriteDB() INodeMutationReceiptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeMutationReceiptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeMutationReceiptDo
	Not(conds ...gen.Condition) INodeMutationReceiptDo
	Or(conds ...gen.Condition) INodeMutationReceiptDo
	Select(conds ...field.Expr) INodeMutationReceiptDo
	Where(conds ...gen.Condition) INodeMutationReceiptDo
	Order(conds ...field.Expr) INodeMutationReceiptDo
	Distinct(cols ...field.Expr) INodeMutationReceiptDo
	Omit(cols ...field.Expr) INodeMutationReceiptDo
	Join(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo
	Group(cols ...field.Expr) INodeMutationReceiptDo
	Having(conds ...gen.Condition) INodeMutationReceiptDo
	Limit(limit int) INodeMutationReceiptDo
	Offset(offset int) INodeMutationReceiptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeMutationReceiptDo
	Unscoped() INodeMutationReceiptDo
	Create(values ...*model.NodeMutationReceipt) error
	CreateInBatches(values []*model.NodeMutationReceipt, batchSize int) error
	Save(values ...*model.NodeMutationReceipt) error
	First() (*model.NodeMutationReceipt, error)
	Take() (*model.NodeMutationReceipt, error)
	Last() (*model.NodeMutationReceipt, error)
	Find() ([]*model.NodeMutationReceipt, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeMutationReceipt, err error)
	FindInBatches(result *[]*model.NodeMutationReceipt, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeMutationReceipt) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeMutationReceiptDo
	Assign(attrs ...field.AssignExpr) INodeMutationReceiptDo
	Joins(fields ...field.RelationField) INodeMutationReceiptDo
	Preload(fields ...field.RelationField) INodeMutationReceiptDo
	FirstOrInit() (*model.NodeMutationReceipt, error)
	FirstOrCreate() (*model.NodeMutationReceipt, error)
	FindByPage(offset int, limit int) (result []*model.NodeMutationReceipt, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeMutationReceiptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeMutationReceiptDo) Debug() INodeMutationReceiptDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeMutationReceiptDo) WithContext(ctx context.Context) INodeMutationReceiptDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeMutationReceiptDo) ReadDB() INodeMutationReceiptDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeMutationReceiptDo) WriteDB() INodeMutationReceiptDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeMutationReceiptDo) Session(config *gorm.Session) INodeMutationReceiptDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeMutationReceiptDo) Clauses(conds ...clause.Expression) INodeMutationReceiptDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeMutationReceiptDo) Returning(value interface{}, columns ...string) INodeMutationReceiptDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeMutationReceiptDo) Not(conds ...gen.Condition) INodeMutationReceiptDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeMutationReceiptDo) Or(conds ...gen.Condition) INodeMutationReceiptDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeMutationReceiptDo) Select(conds ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeMutationReceiptDo) Where(conds ...gen.Condition) INodeMutationReceiptDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeMutationReceiptDo) Order(conds ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeMutationReceiptDo) Distinct(cols ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeMutationReceiptDo) Omit(cols ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeMutationReceiptDo) Join(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeMutationReceiptDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeMutationReceiptDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeMutationReceiptDo) Group(cols ...field.Expr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeMutationReceiptDo) Having(conds ...gen.Condition) INodeMutationReceiptDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeMutationReceiptDo) Limit(limit int) INodeMutationReceiptDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeMutationReceiptDo) Offset(offset int) INodeMutationReceiptDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeMutationReceiptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeMutationReceiptDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeMutationReceiptDo) Unscoped() INodeMutationReceiptDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeMutationReceiptDo) Create(values ...*model.NodeMutationReceipt) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeMutationReceiptDo) CreateInBatches(values []*model.NodeMutationReceipt, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeMutationReceiptDo) Save(values ...*model.NodeMutationReceipt) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeMutationReceiptDo) First() (*model.NodeMutationReceipt, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMutationReceipt), nil
	}
}

func (n nodeMutationReceiptDo) Take() (*model.NodeMutationReceipt, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMutationReceipt), nil
	}
}

func (n nodeMutationReceiptDo) Last() (*model.NodeMutationReceipt, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMutationReceipt), nil
	}
}

func (n nodeMutationReceiptDo) Find() ([]*model.NodeMutationReceipt, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeMutationReceipt), err
}

func (n nodeMutationReceiptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeMutationReceipt, err error) {
	buf := make([]*model.NodeMutationReceipt, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeMutationReceiptDo) FindInBatches(result *[]*model.NodeMutationReceipt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeMutationReceiptDo) Attrs(attrs ...field.AssignExpr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeMutationReceiptDo) Assign(attrs ...field.AssignExpr) INodeMutationReceiptDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeMutationReceiptDo) Joins(fields ...field.RelationField) INodeMutationReceiptDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeMutationReceiptDo) Preload(fields ...field.RelationField) INodeMutationReceiptDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeMutationReceiptDo) FirstOrInit() (*model.NodeMutationReceipt, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMutationReceipt), nil
	}
}

func (n nodeMutationReceiptDo) FirstOrCreate() (*model.NodeMutationReceipt, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeMutationReceipt), nil
	}
}

func (n nodeMutationReceiptDo) FindByPage(offset int, limit int) (result []*model.NodeMutationReceipt, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeMutationReceiptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeMutationReceiptDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeMutationReceiptDo) Delete(models ...*model.NodeMutationReceipt) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeMutationReceiptDo) withDO(do gen.Dao) *nodeMutationReceiptDo {
	n.DO = *do.(*gen.DO)
	return n
}
