// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newNodeResourceTarget(db *gorm.DB, opts ...gen.DOOption) nodeResourceTarget {
	_nodeResourceTarget := nodeResourceTarget{}

	_nodeResourceTarget.nodeResourceTargetDo.UseDB(db, opts...)
	_nodeResourceTarget.nodeResourceTargetDo.UseModel(&model.NodeResourceTarget{})

	tableName := _nodeResourceTarget.nodeResourceTargetDo.TableName()
	_nodeResourceTarget.ALL = field.NewAsterisk(tableName)
	_nodeResourceTarget.NodeID = field.NewInt64(tableName, "node_id")
	_nodeResourceTarget.LibraryID = field.NewInt64(tableName, "library_id")
	_nodeResourceTarget.TargetKind = field.NewString(tableName, "target_kind")
	_nodeResourceTarget.Source = field.NewString(tableName, "source")
	_nodeResourceTarget.UpdatedAt = field.NewTime(tableName, "updated_at")

	_nodeResourceTarget.fillFieldMap()

	return _nodeResourceTarget
}

type nodeResourceTarget struct {
	nodeResourceTargetDo nodeResourceTargetDo

	ALL        field.Asterisk
	NodeID     field.Int64
	LibraryID  field.Int64
	TargetKind field.String
	Source     field.String
	UpdatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (n nodeResourceTarget) Table(newTableName string) *nodeResourceTarget {
	n.nodeResourceTargetDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeResourceTarget) As(alias string) *nodeResourceTarget {
	n.nodeResourceTargetDo.DO = *(n.nodeResourceTargetDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeResourceTarget) updateTableName(table string) *nodeResourceTarget {
	n.ALL = field.NewAsterisk(table)
	n.NodeID = field.NewInt64(table, "node_id")
	n.LibraryID = field.NewInt64(table, "library_id")
	n.TargetKind = field.NewString(table, "target_kind")
	n.Source = field.NewString(table, "source")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *nodeResourceTarget) WithContext(ctx context.Context) INodeResourceTargetDo {
	return n.nodeResourceTargetDo.WithContext(ctx)
}

func (n nodeResourceTarget) TableName() string { return n.nodeResourceTargetDo.TableName() }

func (n nodeResourceTarget) Alias() string { return n.nodeResourceTargetDo.Alias() }

func (n nodeResourceTarget) Columns(cols ...field.Expr) gen.Columns {
	return n.nodeResourceTargetDo.Columns(cols...)
}

func (n *nodeResourceTarget) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeResourceTarget) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 5)
	n.fieldMap["node_id"] = n.NodeID
	n.fieldMap["library_id"] = n.LibraryID
	n.fieldMap["target_kind"] = n.TargetKind
	n.fieldMap["source"] = n.Source
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n nodeResourceTarget) clone(db *gorm.DB) nodeResourceTarget {
	n.nodeResourceTargetDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeResourceTarget) replaceDB(db *gorm.DB) nodeResourceTarget {
	n.nodeResourceTargetDo.ReplaceDB(db)
	return n
}

type nodeResourceTargetDo struct{ gen.DO }

type INodeResourceTargetDo interface {
	gen.SubQuery
	Debug() INodeResourceTargetDo
	WithContext(ctx context.Context) INodeResourceTargetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INodeResourceTargetDo
	WriteDB() INodeResourceTargetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INodeResourceTargetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INodeResourceTargetDo
	Not(conds ...gen.Condition) INodeResourceTargetDo
	Or(conds ...gen.Condition) INodeResourceTargetDo
	Select(conds ...field.Expr) INodeResourceTargetDo
	Where(conds ...gen.Condition) INodeResourceTargetDo
	Order(conds ...field.Expr) INodeResourceTargetDo
	Distinct(cols ...field.Expr) INodeResourceTargetDo
	Omit(cols ...field.Expr) INodeResourceTargetDo
	Join(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo
	RightJoin(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo
	Group(cols ...field.Expr) INodeResourceTargetDo
	Having(conds ...gen.Condition) INodeResourceTargetDo
	Limit(limit int) INodeResourceTargetDo
	Offset(offset int) INodeResourceTargetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INodeResourceTargetDo
	Unscoped() INodeResourceTargetDo
	Create(values ...*model.NodeResourceTarget) error
	CreateInBatches(values []*model.NodeResourceTarget, batchSize int) error
	Save(values ...*model.NodeResourceTarget) error
	First() (*model.NodeResourceTarget, error)
	Take() (*model.NodeResourceTarget, error)
	Last() (*model.NodeResourceTarget, error)
	Find() ([]*model.NodeResourceTarget, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeResourceTarget, err error)
	FindInBatches(result *[]*model.NodeResourceTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NodeResourceTarget) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INodeResourceTargetDo
	Assign(attrs ...field.AssignExpr) INodeResourceTargetDo
	Joins(fields ...field.RelationField) INodeResourceTargetDo
	Preload(fields ...field.RelationField) INodeResourceTargetDo
	FirstOrInit() (*model.NodeResourceTarget, error)
	FirstOrCreate() (*model.NodeResourceTarget, error)
	FindByPage(offset int, limit int) (result []*model.NodeResourceTarget, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INodeResourceTargetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n nodeResourceTargetDo) Debug() INodeResourceTargetDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeResourceTargetDo) WithContext(ctx context.Context) INodeResourceTargetDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeResourceTargetDo) ReadDB() INodeResourceTargetDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeResourceTargetDo) WriteDB() INodeResourceTargetDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeResourceTargetDo) Session(config *gorm.Session) INodeResourceTargetDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeResourceTargetDo) Clauses(conds ...clause.Expression) INodeResourceTargetDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeResourceTargetDo) Returning(value interface{}, columns ...string) INodeResourceTargetDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeResourceTargetDo) Not(conds ...gen.Condition) INodeResourceTargetDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeResourceTargetDo) Or(conds ...gen.Condition) INodeResourceTargetDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeResourceTargetDo) Select(conds ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeResourceTargetDo) Where(conds ...gen.Condition) INodeResourceTargetDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeResourceTargetDo) Order(conds ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeResourceTargetDo) Distinct(cols ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeResourceTargetDo) Omit(cols ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeResourceTargetDo) Join(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeResourceTargetDo) LeftJoin(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeResourceTargetDo) RightJoin(table schema.Tabler, on ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeResourceTargetDo) Group(cols ...field.Expr) INodeResourceTargetDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeResourceTargetDo) Having(conds ...gen.Condition) INodeResourceTargetDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeResourceTargetDo) Limit(limit int) INodeResourceTargetDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeResourceTargetDo) Offset(offset int) INodeResourceTargetDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeResourceTargetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INodeResourceTargetDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeResourceTargetDo) Unscoped() INodeResourceTargetDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeResourceTargetDo) Create(values ...*model.NodeResourceTarget) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeResourceTargetDo) CreateInBatches(values []*model.NodeResourceTarget, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeResourceTargetDo) Save(values ...*model.NodeResourceTarget) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeResourceTargetDo) First() (*model.NodeResourceTarget, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeResourceTarget), nil
	}
}

func (n nodeResourceTargetDo) Take() (*model.NodeResourceTarget, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeResourceTarget), nil
	}
}

func (n nodeResourceTargetDo) Last() (*model.NodeResourceTarget, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeResourceTarget), nil
	}
}

func (n nodeResourceTargetDo) Find() ([]*model.NodeResourceTarget, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeResourceTarget), err
}

func (n nodeResourceTargetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeResourceTarget, err error) {
	buf := make([]*model.NodeResourceTarget, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeResourceTargetDo) FindInBatches(result *[]*model.NodeResourceTarget, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeResourceTargetDo) Attrs(attrs ...field.AssignExpr) INodeResourceTargetDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeResourceTargetDo) Assign(attrs ...field.AssignExpr) INodeResourceTargetDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeResourceTargetDo) Joins(fields ...field.RelationField) INodeResourceTargetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeResourceTargetDo) Preload(fields ...field.RelationField) INodeResourceTargetDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeResourceTargetDo) FirstOrInit() (*model.NodeResourceTarget, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeResourceTarget), nil
	}
}

func (n nodeResourceTargetDo) FirstOrCreate() (*model.NodeResourceTarget, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeResourceTarget), nil
	}
}

func (n nodeResourceTargetDo) FindByPage(offset int, limit int) (result []*model.NodeResourceTarget, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeResourceTargetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeResourceTargetDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeResourceTargetDo) Delete(models ...*model.NodeResourceTarget) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeResourceTargetDo) withDO(do gen.Dao) *nodeResourceTargetDo {
	n.DO = *do.(*gen.DO)
	return n
}
