// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newResourceMonitorSamples(db *gorm.DB, opts ...gen.DOOption) resourceMonitorSamples {
	_resourceMonitorSamples := resourceMonitorSamples{}

	_resourceMonitorSamples.resourceMonitorSamplesDo.UseDB(db, opts...)
	_resourceMonitorSamples.resourceMonitorSamplesDo.UseModel(&model.ResourceMonitorSamples{})

	tableName := _resourceMonitorSamples.resourceMonitorSamplesDo.TableName()
	_resourceMonitorSamples.ALL = field.NewAsterisk(tableName)
	_resourceMonitorSamples.ID = field.NewInt64(tableName, "id")
	_resourceMonitorSamples.ActorID = field.NewString(tableName, "actor_id")
	_resourceMonitorSamples.Scope = field.NewString(tableName, "scope")
	_resourceMonitorSamples.LibraryID = field.NewInt64(tableName, "library_id")
	_resourceMonitorSamples.GeneratedAt = field.NewTime(tableName, "generated_at")
	_resourceMonitorSamples.ProviderCount = field.NewInt32(tableName, "provider_count")
	_resourceMonitorSamples.BucketCount = field.NewInt32(tableName, "bucket_count")
	_resourceMonitorSamples.ObjectCount = field.NewInt64(tableName, "object_count")
	_resourceMonitorSamples.FileRefCount = field.NewInt64(tableName, "file_ref_count")
	_resourceMonitorSamples.PhysicalBytes = field.NewInt64(tableName, "physical_bytes")
	_resourceMonitorSamples.VisibleObjectCount = field.NewInt64(tableName, "visible_object_count")
	_resourceMonitorSamples.VisibleFileRefCount = field.NewInt64(tableName, "visible_file_ref_count")
	_resourceMonitorSamples.VisibleBytes = field.NewInt64(tableName, "visible_bytes")
	_resourceMonitorSamples.RecycleObjectCount = field.NewInt64(tableName, "recycle_object_count")
	_resourceMonitorSamples.RecycleFileRefCount = field.NewInt64(tableName, "recycle_file_ref_count")
	_resourceMonitorSamples.RecycleBytes = field.NewInt64(tableName, "recycle_bytes")
	_resourceMonitorSamples.OrphanObjectCount = field.NewInt64(tableName, "orphan_object_count")
	_resourceMonitorSamples.OrphanBytes = field.NewInt64(tableName, "orphan_bytes")
	_resourceMonitorSamples.UnmatchedCount = field.NewInt32(tableName, "unmatched_count")
	_resourceMonitorSamples.LegacyProviderCount = field.NewInt32(tableName, "legacy_provider_count")
	_resourceMonitorSamples.ProbeTotal = field.NewInt32(tableName, "probe_total")
	_resourceMonitorSamples.ProbeOk = field.NewInt32(tableName, "probe_ok")
	_resourceMonitorSamples.ProbeError = field.NewInt32(tableName, "probe_error")
	_resourceMonitorSamples.ProbeUnknown = field.NewInt32(tableName, "probe_unknown")
	_resourceMonitorSamples.DistributionError = field.NewString(tableName, "distribution_error")
	_resourceMonitorSamples.SnapshotJSON = field.NewString(tableName, "snapshot_json")
	_resourceMonitorSamples.CreatedAt = field.NewTime(tableName, "created_at")

	_resourceMonitorSamples.fillFieldMap()

	return _resourceMonitorSamples
}

type resourceMonitorSamples struct {
	resourceMonitorSamplesDo resourceMonitorSamplesDo

	ALL                 field.Asterisk
	ID                  field.Int64
	ActorID             field.String
	Scope               field.String
	LibraryID           field.Int64
	GeneratedAt         field.Time
	ProviderCount       field.Int32
	BucketCount         field.Int32
	ObjectCount         field.Int64
	FileRefCount        field.Int64
	PhysicalBytes       field.Int64
	VisibleObjectCount  field.Int64
	VisibleFileRefCount field.Int64
	VisibleBytes        field.Int64
	RecycleObjectCount  field.Int64
	RecycleFileRefCount field.Int64
	RecycleBytes        field.Int64
	OrphanObjectCount   field.Int64
	OrphanBytes         field.Int64
	UnmatchedCount      field.Int32
	LegacyProviderCount field.Int32
	ProbeTotal          field.Int32
	ProbeOk             field.Int32
	ProbeError          field.Int32
	ProbeUnknown        field.Int32
	DistributionError   field.String
	SnapshotJSON        field.String
	CreatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (r resourceMonitorSamples) Table(newTableName string) *resourceMonitorSamples {
	r.resourceMonitorSamplesDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r resourceMonitorSamples) As(alias string) *resourceMonitorSamples {
	r.resourceMonitorSamplesDo.DO = *(r.resourceMonitorSamplesDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *resourceMonitorSamples) updateTableName(table string) *resourceMonitorSamples {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.ActorID = field.NewString(table, "actor_id")
	r.Scope = field.NewString(table, "scope")
	r.LibraryID = field.NewInt64(table, "library_id")
	r.GeneratedAt = field.NewTime(table, "generated_at")
	r.ProviderCount = field.NewInt32(table, "provider_count")
	r.BucketCount = field.NewInt32(table, "bucket_count")
	r.ObjectCount = field.NewInt64(table, "object_count")
	r.FileRefCount = field.NewInt64(table, "file_ref_count")
	r.PhysicalBytes = field.NewInt64(table, "physical_bytes")
	r.VisibleObjectCount = field.NewInt64(table, "visible_object_count")
	r.VisibleFileRefCount = field.NewInt64(table, "visible_file_ref_count")
	r.VisibleBytes = field.NewInt64(table, "visible_bytes")
	r.RecycleObjectCount = field.NewInt64(table, "recycle_object_count")
	r.RecycleFileRefCount = field.NewInt64(table, "recycle_file_ref_count")
	r.RecycleBytes = field.NewInt64(table, "recycle_bytes")
	r.OrphanObjectCount = field.NewInt64(table, "orphan_object_count")
	r.OrphanBytes = field.NewInt64(table, "orphan_bytes")
	r.UnmatchedCount = field.NewInt32(table, "unmatched_count")
	r.LegacyProviderCount = field.NewInt32(table, "legacy_provider_count")
	r.ProbeTotal = field.NewInt32(table, "probe_total")
	r.ProbeOk = field.NewInt32(table, "probe_ok")
	r.ProbeError = field.NewInt32(table, "probe_error")
	r.ProbeUnknown = field.NewInt32(table, "probe_unknown")
	r.DistributionError = field.NewString(table, "distribution_error")
	r.SnapshotJSON = field.NewString(table, "snapshot_json")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *resourceMonitorSamples) WithContext(ctx context.Context) IResourceMonitorSamplesDo {
	return r.resourceMonitorSamplesDo.WithContext(ctx)
}

func (r resourceMonitorSamples) TableName() string { return r.resourceMonitorSamplesDo.TableName() }

func (r resourceMonitorSamples) Alias() string { return r.resourceMonitorSamplesDo.Alias() }

func (r resourceMonitorSamples) Columns(cols ...field.Expr) gen.Columns {
	return r.resourceMonitorSamplesDo.Columns(cols...)
}

func (r *resourceMonitorSamples) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *resourceMonitorSamples) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 27)
	r.fieldMap["id"] = r.ID
	r.fieldMap["actor_id"] = r.ActorID
	r.fieldMap["scope"] = r.Scope
	r.fieldMap["library_id"] = r.LibraryID
	r.fieldMap["generated_at"] = r.GeneratedAt
	r.fieldMap["provider_count"] = r.ProviderCount
	r.fieldMap["bucket_count"] = r.BucketCount
	r.fieldMap["object_count"] = r.ObjectCount
	r.fieldMap["file_ref_count"] = r.FileRefCount
	r.fieldMap["physical_bytes"] = r.PhysicalBytes
	r.fieldMap["visible_object_count"] = r.VisibleObjectCount
	r.fieldMap["visible_file_ref_count"] = r.VisibleFileRefCount
	r.fieldMap["visible_bytes"] = r.VisibleBytes
	r.fieldMap["recycle_object_count"] = r.RecycleObjectCount
	r.fieldMap["recycle_file_ref_count"] = r.RecycleFileRefCount
	r.fieldMap["recycle_bytes"] = r.RecycleBytes
	r.fieldMap["orphan_object_count"] = r.OrphanObjectCount
	r.fieldMap["orphan_bytes"] = r.OrphanBytes
	r.fieldMap["unmatched_count"] = r.UnmatchedCount
	r.fieldMap["legacy_provider_count"] = r.LegacyProviderCount
	r.fieldMap["probe_total"] = r.ProbeTotal
	r.fieldMap["probe_ok"] = r.ProbeOk
	r.fieldMap["probe_error"] = r.ProbeError
	r.fieldMap["probe_unknown"] = r.ProbeUnknown
	r.fieldMap["distribution_error"] = r.DistributionError
	r.fieldMap["snapshot_json"] = r.SnapshotJSON
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r resourceMonitorSamples) clone(db *gorm.DB) resourceMonitorSamples {
	r.resourceMonitorSamplesDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r resourceMonitorSamples) replaceDB(db *gorm.DB) resourceMonitorSamples {
	r.resourceMonitorSamplesDo.ReplaceDB(db)
	return r
}

type resourceMonitorSamplesDo struct{ gen.DO }

type IResourceMonitorSamplesDo interface {
	gen.SubQuery
	Debug() IResourceMonitorSamplesDo
	WithContext(ctx context.Context) IResourceMonitorSamplesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResourceMonitorSamplesDo
	WriteDB() IResourceMonitorSamplesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResourceMonitorSamplesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResourceMonitorSamplesDo
	Not(conds ...gen.Condition) IResourceMonitorSamplesDo
	Or(conds ...gen.Condition) IResourceMonitorSamplesDo
	Select(conds ...field.Expr) IResourceMonitorSamplesDo
	Where(conds ...gen.Condition) IResourceMonitorSamplesDo
	Order(conds ...field.Expr) IResourceMonitorSamplesDo
	Distinct(cols ...field.Expr) IResourceMonitorSamplesDo
	Omit(cols ...field.Expr) IResourceMonitorSamplesDo
	Join(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo
	Group(cols ...field.Expr) IResourceMonitorSamplesDo
	Having(conds ...gen.Condition) IResourceMonitorSamplesDo
	Limit(limit int) IResourceMonitorSamplesDo
	Offset(offset int) IResourceMonitorSamplesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceMonitorSamplesDo
	Unscoped() IResourceMonitorSamplesDo
	Create(values ...*model.ResourceMonitorSamples) error
	CreateInBatches(values []*model.ResourceMonitorSamples, batchSize int) error
	Save(values ...*model.ResourceMonitorSamples) error
	First() (*model.ResourceMonitorSamples, error)
	Take() (*model.ResourceMonitorSamples, error)
	Last() (*model.ResourceMonitorSamples, error)
	Find() ([]*model.ResourceMonitorSamples, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceMonitorSamples, err error)
	FindInBatches(result *[]*model.ResourceMonitorSamples, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ResourceMonitorSamples) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResourceMonitorSamplesDo
	Assign(attrs ...field.AssignExpr) IResourceMonitorSamplesDo
	Joins(fields ...field.RelationField) IResourceMonitorSamplesDo
	Preload(fields ...field.RelationField) IResourceMonitorSamplesDo
	FirstOrInit() (*model.ResourceMonitorSamples, error)
	FirstOrCreate() (*model.ResourceMonitorSamples, error)
	FindByPage(offset int, limit int) (result []*model.ResourceMonitorSamples, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResourceMonitorSamplesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r resourceMonitorSamplesDo) Debug() IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Debug())
}

func (r resourceMonitorSamplesDo) WithContext(ctx context.Context) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r resourceMonitorSamplesDo) ReadDB() IResourceMonitorSamplesDo {
	return r.Clauses(dbresolver.Read)
}

func (r resourceMonitorSamplesDo) WriteDB() IResourceMonitorSamplesDo {
	return r.Clauses(dbresolver.Write)
}

func (r resourceMonitorSamplesDo) Session(config *gorm.Session) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Session(config))
}

func (r resourceMonitorSamplesDo) Clauses(conds ...clause.Expression) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r resourceMonitorSamplesDo) Returning(value interface{}, columns ...string) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r resourceMonitorSamplesDo) Not(conds ...gen.Condition) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r resourceMonitorSamplesDo) Or(conds ...gen.Condition) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r resourceMonitorSamplesDo) Select(conds ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r resourceMonitorSamplesDo) Where(conds ...gen.Condition) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r resourceMonitorSamplesDo) Order(conds ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r resourceMonitorSamplesDo) Distinct(cols ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r resourceMonitorSamplesDo) Omit(cols ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r resourceMonitorSamplesDo) Join(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r resourceMonitorSamplesDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r resourceMonitorSamplesDo) RightJoin(table schema.Tabler, on ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r resourceMonitorSamplesDo) Group(cols ...field.Expr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r resourceMonitorSamplesDo) Having(conds ...gen.Condition) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r resourceMonitorSamplesDo) Limit(limit int) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r resourceMonitorSamplesDo) Offset(offset int) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r resourceMonitorSamplesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r resourceMonitorSamplesDo) Unscoped() IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Unscoped())
}

func (r resourceMonitorSamplesDo) Create(values ...*model.ResourceMonitorSamples) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r resourceMonitorSamplesDo) CreateInBatches(values []*model.ResourceMonitorSamples, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r resourceMonitorSamplesDo) Save(values ...*model.ResourceMonitorSamples) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r resourceMonitorSamplesDo) First() (*model.ResourceMonitorSamples, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceMonitorSamples), nil
	}
}

func (r resourceMonitorSamplesDo) Take() (*model.ResourceMonitorSamples, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceMonitorSamples), nil
	}
}

func (r resourceMonitorSamplesDo) Last() (*model.ResourceMonitorSamples, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceMonitorSamples), nil
	}
}

func (r resourceMonitorSamplesDo) Find() ([]*model.ResourceMonitorSamples, error) {
	result, err := r.DO.Find()
	return result.([]*model.ResourceMonitorSamples), err
}

func (r resourceMonitorSamplesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ResourceMonitorSamples, err error) {
	buf := make([]*model.ResourceMonitorSamples, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r resourceMonitorSamplesDo) FindInBatches(result *[]*model.ResourceMonitorSamples, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r resourceMonitorSamplesDo) Attrs(attrs ...field.AssignExpr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r resourceMonitorSamplesDo) Assign(attrs ...field.AssignExpr) IResourceMonitorSamplesDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r resourceMonitorSamplesDo) Joins(fields ...field.RelationField) IResourceMonitorSamplesDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r resourceMonitorSamplesDo) Preload(fields ...field.RelationField) IResourceMonitorSamplesDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r resourceMonitorSamplesDo) FirstOrInit() (*model.ResourceMonitorSamples, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceMonitorSamples), nil
	}
}

func (r resourceMonitorSamplesDo) FirstOrCreate() (*model.ResourceMonitorSamples, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ResourceMonitorSamples), nil
	}
}

func (r resourceMonitorSamplesDo) FindByPage(offset int, limit int) (result []*model.ResourceMonitorSamples, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r resourceMonitorSamplesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r resourceMonitorSamplesDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r resourceMonitorSamplesDo) Delete(models ...*model.ResourceMonitorSamples) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *resourceMonitorSamplesDo) withDO(do gen.Dao) *resourceMonitorSamplesDo {
	r.DO = *do.(*gen.DO)
	return r
}
