// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newStorageObject(db *gorm.DB, opts ...gen.DOOption) storageObject {
	_storageObject := storageObject{}

	_storageObject.storageObjectDo.UseDB(db, opts...)
	_storageObject.storageObjectDo.UseModel(&model.StorageObject{})

	tableName := _storageObject.storageObjectDo.TableName()
	_storageObject.ALL = field.NewAsterisk(tableName)
	_storageObject.ID = field.NewInt64(tableName, "id")
	_storageObject.LibraryID = field.NewInt64(tableName, "library_id")
	_storageObject.Provider = field.NewString(tableName, "provider")
	_storageObject.Bucket = field.NewString(tableName, "bucket")
	_storageObject.ObjectKey = field.NewString(tableName, "object_key")
	_storageObject.VersionID = field.NewString(tableName, "version_id")
	_storageObject.Etag = field.NewString(tableName, "etag")
	_storageObject.ChecksumSha256 = field.NewString(tableName, "checksum_sha256")
	_storageObject.StorageClass = field.NewString(tableName, "storage_class")
	_storageObject.ContentLength = field.NewInt64(tableName, "content_length")
	_storageObject.ContentType = field.NewString(tableName, "content_type")
	_storageObject.Extra = field.NewString(tableName, "extra")
	_storageObject.DeletedAt = field.NewField(tableName, "deleted_at")
	_storageObject.CreatedAt = field.NewTime(tableName, "created_at")
	_storageObject.UpdatedAt = field.NewTime(tableName, "updated_at")

	_storageObject.fillFieldMap()

	return _storageObject
}

type storageObject struct {
	storageObjectDo storageObjectDo

	ALL            field.Asterisk
	ID             field.Int64
	LibraryID      field.Int64
	Provider       field.String
	Bucket         field.String
	ObjectKey      field.String // 对象存储中的真实 key
	VersionID      field.String
	Etag           field.String
	ChecksumSha256 field.String
	StorageClass   field.String
	ContentLength  field.Int64
	ContentType    field.String
	Extra          field.String // 厂商扩展字段
	DeletedAt      field.Field
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (s storageObject) Table(newTableName string) *storageObject {
	s.storageObjectDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s storageObject) As(alias string) *storageObject {
	s.storageObjectDo.DO = *(s.storageObjectDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *storageObject) updateTableName(table string) *storageObject {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.LibraryID = field.NewInt64(table, "library_id")
	s.Provider = field.NewString(table, "provider")
	s.Bucket = field.NewString(table, "bucket")
	s.ObjectKey = field.NewString(table, "object_key")
	s.VersionID = field.NewString(table, "version_id")
	s.Etag = field.NewString(table, "etag")
	s.ChecksumSha256 = field.NewString(table, "checksum_sha256")
	s.StorageClass = field.NewString(table, "storage_class")
	s.ContentLength = field.NewInt64(table, "content_length")
	s.ContentType = field.NewString(table, "content_type")
	s.Extra = field.NewString(table, "extra")
	s.DeletedAt = field.NewField(table, "deleted_at")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *storageObject) WithContext(ctx context.Context) IStorageObjectDo {
	return s.storageObjectDo.WithContext(ctx)
}

func (s storageObject) TableName() string { return s.storageObjectDo.TableName() }

func (s storageObject) Alias() string { return s.storageObjectDo.Alias() }

func (s storageObject) Columns(cols ...field.Expr) gen.Columns {
	return s.storageObjectDo.Columns(cols...)
}

func (s *storageObject) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *storageObject) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 15)
	s.fieldMap["id"] = s.ID
	s.fieldMap["library_id"] = s.LibraryID
	s.fieldMap["provider"] = s.Provider
	s.fieldMap["bucket"] = s.Bucket
	s.fieldMap["object_key"] = s.ObjectKey
	s.fieldMap["version_id"] = s.VersionID
	s.fieldMap["etag"] = s.Etag
	s.fieldMap["checksum_sha256"] = s.ChecksumSha256
	s.fieldMap["storage_class"] = s.StorageClass
	s.fieldMap["content_length"] = s.ContentLength
	s.fieldMap["content_type"] = s.ContentType
	s.fieldMap["extra"] = s.Extra
	s.fieldMap["deleted_at"] = s.DeletedAt
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s storageObject) clone(db *gorm.DB) storageObject {
	s.storageObjectDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s storageObject) replaceDB(db *gorm.DB) storageObject {
	s.storageObjectDo.ReplaceDB(db)
	return s
}

type storageObjectDo struct{ gen.DO }

type IStorageObjectDo interface {
	gen.SubQuery
	Debug() IStorageObjectDo
	WithContext(ctx context.Context) IStorageObjectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStorageObjectDo
	WriteDB() IStorageObjectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStorageObjectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStorageObjectDo
	Not(conds ...gen.Condition) IStorageObjectDo
	Or(conds ...gen.Condition) IStorageObjectDo
	Select(conds ...field.Expr) IStorageObjectDo
	Where(conds ...gen.Condition) IStorageObjectDo
	Order(conds ...field.Expr) IStorageObjectDo
	Distinct(cols ...field.Expr) IStorageObjectDo
	Omit(cols ...field.Expr) IStorageObjectDo
	Join(table schema.Tabler, on ...field.Expr) IStorageObjectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStorageObjectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStorageObjectDo
	Group(cols ...field.Expr) IStorageObjectDo
	Having(conds ...gen.Condition) IStorageObjectDo
	Limit(limit int) IStorageObjectDo
	Offset(offset int) IStorageObjectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageObjectDo
	Unscoped() IStorageObjectDo
	Create(values ...*model.StorageObject) error
	CreateInBatches(values []*model.StorageObject, batchSize int) error
	Save(values ...*model.StorageObject) error
	First() (*model.StorageObject, error)
	Take() (*model.StorageObject, error)
	Last() (*model.StorageObject, error)
	Find() ([]*model.StorageObject, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StorageObject, err error)
	FindInBatches(result *[]*model.StorageObject, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StorageObject) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStorageObjectDo
	Assign(attrs ...field.AssignExpr) IStorageObjectDo
	Joins(fields ...field.RelationField) IStorageObjectDo
	Preload(fields ...field.RelationField) IStorageObjectDo
	FirstOrInit() (*model.StorageObject, error)
	FirstOrCreate() (*model.StorageObject, error)
	FindByPage(offset int, limit int) (result []*model.StorageObject, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStorageObjectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s storageObjectDo) Debug() IStorageObjectDo {
	return s.withDO(s.DO.Debug())
}

func (s storageObjectDo) WithContext(ctx context.Context) IStorageObjectDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s storageObjectDo) ReadDB() IStorageObjectDo {
	return s.Clauses(dbresolver.Read)
}

func (s storageObjectDo) WriteDB() IStorageObjectDo {
	return s.Clauses(dbresolver.Write)
}

func (s storageObjectDo) Session(config *gorm.Session) IStorageObjectDo {
	return s.withDO(s.DO.Session(config))
}

func (s storageObjectDo) Clauses(conds ...clause.Expression) IStorageObjectDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s storageObjectDo) Returning(value interface{}, columns ...string) IStorageObjectDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s storageObjectDo) Not(conds ...gen.Condition) IStorageObjectDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s storageObjectDo) Or(conds ...gen.Condition) IStorageObjectDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s storageObjectDo) Select(conds ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s storageObjectDo) Where(conds ...gen.Condition) IStorageObjectDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s storageObjectDo) Order(conds ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s storageObjectDo) Distinct(cols ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s storageObjectDo) Omit(cols ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s storageObjectDo) Join(table schema.Tabler, on ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s storageObjectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s storageObjectDo) RightJoin(table schema.Tabler, on ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s storageObjectDo) Group(cols ...field.Expr) IStorageObjectDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s storageObjectDo) Having(conds ...gen.Condition) IStorageObjectDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s storageObjectDo) Limit(limit int) IStorageObjectDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s storageObjectDo) Offset(offset int) IStorageObjectDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s storageObjectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStorageObjectDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s storageObjectDo) Unscoped() IStorageObjectDo {
	return s.withDO(s.DO.Unscoped())
}

func (s storageObjectDo) Create(values ...*model.StorageObject) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s storageObjectDo) CreateInBatches(values []*model.StorageObject, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s storageObjectDo) Save(values ...*model.StorageObject) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s storageObjectDo) First() (*model.StorageObject, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StorageObject), nil
	}
}

func (s storageObjectDo) Take() (*model.StorageObject, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StorageObject), nil
	}
}

func (s storageObjectDo) Last() (*model.StorageObject, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StorageObject), nil
	}
}

func (s storageObjectDo) Find() ([]*model.StorageObject, error) {
	result, err := s.DO.Find()
	return result.([]*model.StorageObject), err
}

func (s storageObjectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StorageObject, err error) {
	buf := make([]*model.StorageObject, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s storageObjectDo) FindInBatches(result *[]*model.StorageObject, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s storageObjectDo) Attrs(attrs ...field.AssignExpr) IStorageObjectDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s storageObjectDo) Assign(attrs ...field.AssignExpr) IStorageObjectDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s storageObjectDo) Joins(fields ...field.RelationField) IStorageObjectDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s storageObjectDo) Preload(fields ...field.RelationField) IStorageObjectDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s storageObjectDo) FirstOrInit() (*model.StorageObject, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StorageObject), nil
	}
}

func (s storageObjectDo) FirstOrCreate() (*model.StorageObject, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StorageObject), nil
	}
}

func (s storageObjectDo) FindByPage(offset int, limit int) (result []*model.StorageObject, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s storageObjectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s storageObjectDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s storageObjectDo) Delete(models ...*model.StorageObject) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *storageObjectDo) withDO(do gen.Dao) *storageObjectDo {
	s.DO = *do.(*gen.DO)
	return s
}
