// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newTagTargetKind(db *gorm.DB, opts ...gen.DOOption) tagTargetKind {
	_tagTargetKind := tagTargetKind{}

	_tagTargetKind.tagTargetKindDo.UseDB(db, opts...)
	_tagTargetKind.tagTargetKindDo.UseModel(&model.TagTargetKind{})

	tableName := _tagTargetKind.tagTargetKindDo.TableName()
	_tagTargetKind.ALL = field.NewAsterisk(tableName)
	_tagTargetKind.Key = field.NewString(tableName, "key")
	_tagTargetKind.Label = field.NewString(tableName, "label")
	_tagTargetKind.ResourceKind = field.NewString(tableName, "resource_kind")
	_tagTargetKind.SortOrder = field.NewInt32(tableName, "sort_order")
	_tagTargetKind.Enabled = field.NewBool(tableName, "enabled")
	_tagTargetKind.Description = field.NewString(tableName, "description")
	_tagTargetKind.CreatedAt = field.NewTime(tableName, "created_at")
	_tagTargetKind.UpdatedAt = field.NewTime(tableName, "updated_at")

	_tagTargetKind.fillFieldMap()

	return _tagTargetKind
}

type tagTargetKind struct {
	tagTargetKindDo tagTargetKindDo

	ALL          field.Asterisk
	Key          field.String
	Label        field.String
	ResourceKind field.String
	SortOrder    field.Int32
	Enabled      field.Bool
	Description  field.String
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (t tagTargetKind) Table(newTableName string) *tagTargetKind {
	t.tagTargetKindDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagTargetKind) As(alias string) *tagTargetKind {
	t.tagTargetKindDo.DO = *(t.tagTargetKindDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagTargetKind) updateTableName(table string) *tagTargetKind {
	t.ALL = field.NewAsterisk(table)
	t.Key = field.NewString(table, "key")
	t.Label = field.NewString(table, "label")
	t.ResourceKind = field.NewString(table, "resource_kind")
	t.SortOrder = field.NewInt32(table, "sort_order")
	t.Enabled = field.NewBool(table, "enabled")
	t.Description = field.NewString(table, "description")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *tagTargetKind) WithContext(ctx context.Context) ITagTargetKindDo {
	return t.tagTargetKindDo.WithContext(ctx)
}

func (t tagTargetKind) TableName() string { return t.tagTargetKindDo.TableName() }

func (t tagTargetKind) Alias() string { return t.tagTargetKindDo.Alias() }

func (t tagTargetKind) Columns(cols ...field.Expr) gen.Columns {
	return t.tagTargetKindDo.Columns(cols...)
}

func (t *tagTargetKind) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagTargetKind) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["key"] = t.Key
	t.fieldMap["label"] = t.Label
	t.fieldMap["resource_kind"] = t.ResourceKind
	t.fieldMap["sort_order"] = t.SortOrder
	t.fieldMap["enabled"] = t.Enabled
	t.fieldMap["description"] = t.Description
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t tagTargetKind) clone(db *gorm.DB) tagTargetKind {
	t.tagTargetKindDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagTargetKind) replaceDB(db *gorm.DB) tagTargetKind {
	t.tagTargetKindDo.ReplaceDB(db)
	return t
}

type tagTargetKindDo struct{ gen.DO }

type ITagTargetKindDo interface {
	gen.SubQuery
	Debug() ITagTargetKindDo
	WithContext(ctx context.Context) ITagTargetKindDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITagTargetKindDo
	WriteDB() ITagTargetKindDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITagTargetKindDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITagTargetKindDo
	Not(conds ...gen.Condition) ITagTargetKindDo
	Or(conds ...gen.Condition) ITagTargetKindDo
	Select(conds ...field.Expr) ITagTargetKindDo
	Where(conds ...gen.Condition) ITagTargetKindDo
	Order(conds ...field.Expr) ITagTargetKindDo
	Distinct(cols ...field.Expr) ITagTargetKindDo
	Omit(cols ...field.Expr) ITagTargetKindDo
	Join(table schema.Tabler, on ...field.Expr) ITagTargetKindDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITagTargetKindDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITagTargetKindDo
	Group(cols ...field.Expr) ITagTargetKindDo
	Having(conds ...gen.Condition) ITagTargetKindDo
	Limit(limit int) ITagTargetKindDo
	Offset(offset int) ITagTargetKindDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITagTargetKindDo
	Unscoped() ITagTargetKindDo
	Create(values ...*model.TagTargetKind) error
	CreateInBatches(values []*model.TagTargetKind, batchSize int) error
	Save(values ...*model.TagTargetKind) error
	First() (*model.TagTargetKind, error)
	Take() (*model.TagTargetKind, error)
	Last() (*model.TagTargetKind, error)
	Find() ([]*model.TagTargetKind, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagTargetKind, err error)
	FindInBatches(result *[]*model.TagTargetKind, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TagTargetKind) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITagTargetKindDo
	Assign(attrs ...field.AssignExpr) ITagTargetKindDo
	Joins(fields ...field.RelationField) ITagTargetKindDo
	Preload(fields ...field.RelationField) ITagTargetKindDo
	FirstOrInit() (*model.TagTargetKind, error)
	FirstOrCreate() (*model.TagTargetKind, error)
	FindByPage(offset int, limit int) (result []*model.TagTargetKind, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITagTargetKindDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tagTargetKindDo) Debug() ITagTargetKindDo {
	return t.withDO(t.DO.Debug())
}

func (t tagTargetKindDo) WithContext(ctx context.Context) ITagTargetKindDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagTargetKindDo) ReadDB() ITagTargetKindDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagTargetKindDo) WriteDB() ITagTargetKindDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagTargetKindDo) Session(config *gorm.Session) ITagTargetKindDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagTargetKindDo) Clauses(conds ...clause.Expression) ITagTargetKindDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagTargetKindDo) Returning(value interface{}, columns ...string) ITagTargetKindDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagTargetKindDo) Not(conds ...gen.Condition) ITagTargetKindDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagTargetKindDo) Or(conds ...gen.Condition) ITagTargetKindDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagTargetKindDo) Select(conds ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagTargetKindDo) Where(conds ...gen.Condition) ITagTargetKindDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagTargetKindDo) Order(conds ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagTargetKindDo) Distinct(cols ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagTargetKindDo) Omit(cols ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagTargetKindDo) Join(table schema.Tabler, on ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagTargetKindDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagTargetKindDo) RightJoin(table schema.Tabler, on ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagTargetKindDo) Group(cols ...field.Expr) ITagTargetKindDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagTargetKindDo) Having(conds ...gen.Condition) ITagTargetKindDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagTargetKindDo) Limit(limit int) ITagTargetKindDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagTargetKindDo) Offset(offset int) ITagTargetKindDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagTargetKindDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITagTargetKindDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagTargetKindDo) Unscoped() ITagTargetKindDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagTargetKindDo) Create(values ...*model.TagTargetKind) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagTargetKindDo) CreateInBatches(values []*model.TagTargetKind, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagTargetKindDo) Save(values ...*model.TagTargetKind) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagTargetKindDo) First() (*model.TagTargetKind, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagTargetKind), nil
	}
}

func (t tagTargetKindDo) Take() (*model.TagTargetKind, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagTargetKind), nil
	}
}

func (t tagTargetKindDo) Last() (*model.TagTargetKind, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagTargetKind), nil
	}
}

func (t tagTargetKindDo) Find() ([]*model.TagTargetKind, error) {
	result, err := t.DO.Find()
	return result.([]*model.TagTargetKind), err
}

func (t tagTargetKindDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagTargetKind, err error) {
	buf := make([]*model.TagTargetKind, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagTargetKindDo) FindInBatches(result *[]*model.TagTargetKind, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagTargetKindDo) Attrs(attrs ...field.AssignExpr) ITagTargetKindDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagTargetKindDo) Assign(attrs ...field.AssignExpr) ITagTargetKindDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagTargetKindDo) Joins(fields ...field.RelationField) ITagTargetKindDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagTargetKindDo) Preload(fields ...field.RelationField) ITagTargetKindDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagTargetKindDo) FirstOrInit() (*model.TagTargetKind, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagTargetKind), nil
	}
}

func (t tagTargetKindDo) FirstOrCreate() (*model.TagTargetKind, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagTargetKind), nil
	}
}

func (t tagTargetKindDo) FindByPage(offset int, limit int) (result []*model.TagTargetKind, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagTargetKindDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagTargetKindDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagTargetKindDo) Delete(models ...*model.TagTargetKind) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagTargetKindDo) withDO(do gen.Dao) *tagTargetKindDo {
	t.DO = *do.(*gen.DO)
	return t
}
