// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newTagAlias(db *gorm.DB, opts ...gen.DOOption) tagAlias {
	_tagAlias := tagAlias{}

	_tagAlias.tagAliasDo.UseDB(db, opts...)
	_tagAlias.tagAliasDo.UseModel(&model.TagAlias{})

	tableName := _tagAlias.tagAliasDo.TableName()
	_tagAlias.ALL = field.NewAsterisk(tableName)
	_tagAlias.ID = field.NewInt64(tableName, "id")
	_tagAlias.TagID = field.NewInt64(tableName, "tag_id")
	_tagAlias.Alias_ = field.NewString(tableName, "alias")
	_tagAlias.NormalizedAlias = field.NewString(tableName, "normalized_alias")
	_tagAlias.OwnerUserID = field.NewInt64(tableName, "owner_user_id")
	_tagAlias.CreatedAt = field.NewTime(tableName, "created_at")
	_tagAlias.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tagAlias.DeletedAt = field.NewField(tableName, "deleted_at")

	_tagAlias.fillFieldMap()

	return _tagAlias
}

type tagAlias struct {
	tagAliasDo tagAliasDo

	ALL             field.Asterisk
	ID              field.Int64
	TagID           field.Int64
	Alias_          field.String
	NormalizedAlias field.String
	OwnerUserID     field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field

	fieldMap map[string]field.Expr
}

func (t tagAlias) Table(newTableName string) *tagAlias {
	t.tagAliasDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagAlias) As(alias string) *tagAlias {
	t.tagAliasDo.DO = *(t.tagAliasDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagAlias) updateTableName(table string) *tagAlias {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TagID = field.NewInt64(table, "tag_id")
	t.Alias_ = field.NewString(table, "alias")
	t.NormalizedAlias = field.NewString(table, "normalized_alias")
	t.OwnerUserID = field.NewInt64(table, "owner_user_id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tagAlias) WithContext(ctx context.Context) ITagAliasDo { return t.tagAliasDo.WithContext(ctx) }

func (t tagAlias) TableName() string { return t.tagAliasDo.TableName() }

func (t tagAlias) Alias() string { return t.tagAliasDo.Alias() }

func (t tagAlias) Columns(cols ...field.Expr) gen.Columns { return t.tagAliasDo.Columns(cols...) }

func (t *tagAlias) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagAlias) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tag_id"] = t.TagID
	t.fieldMap["alias"] = t.Alias_
	t.fieldMap["normalized_alias"] = t.NormalizedAlias
	t.fieldMap["owner_user_id"] = t.OwnerUserID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tagAlias) clone(db *gorm.DB) tagAlias {
	t.tagAliasDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagAlias) replaceDB(db *gorm.DB) tagAlias {
	t.tagAliasDo.ReplaceDB(db)
	return t
}

type tagAliasDo struct{ gen.DO }

type ITagAliasDo interface {
	gen.SubQuery
	Debug() ITagAliasDo
	WithContext(ctx context.Context) ITagAliasDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITagAliasDo
	WriteDB() ITagAliasDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITagAliasDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITagAliasDo
	Not(conds ...gen.Condition) ITagAliasDo
	Or(conds ...gen.Condition) ITagAliasDo
	Select(conds ...field.Expr) ITagAliasDo
	Where(conds ...gen.Condition) ITagAliasDo
	Order(conds ...field.Expr) ITagAliasDo
	Distinct(cols ...field.Expr) ITagAliasDo
	Omit(cols ...field.Expr) ITagAliasDo
	Join(table schema.Tabler, on ...field.Expr) ITagAliasDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITagAliasDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITagAliasDo
	Group(cols ...field.Expr) ITagAliasDo
	Having(conds ...gen.Condition) ITagAliasDo
	Limit(limit int) ITagAliasDo
	Offset(offset int) ITagAliasDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITagAliasDo
	Unscoped() ITagAliasDo
	Create(values ...*model.TagAlias) error
	CreateInBatches(values []*model.TagAlias, batchSize int) error
	Save(values ...*model.TagAlias) error
	First() (*model.TagAlias, error)
	Take() (*model.TagAlias, error)
	Last() (*model.TagAlias, error)
	Find() ([]*model.TagAlias, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagAlias, err error)
	FindInBatches(result *[]*model.TagAlias, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TagAlias) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITagAliasDo
	Assign(attrs ...field.AssignExpr) ITagAliasDo
	Joins(fields ...field.RelationField) ITagAliasDo
	Preload(fields ...field.RelationField) ITagAliasDo
	FirstOrInit() (*model.TagAlias, error)
	FirstOrCreate() (*model.TagAlias, error)
	FindByPage(offset int, limit int) (result []*model.TagAlias, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITagAliasDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tagAliasDo) Debug() ITagAliasDo {
	return t.withDO(t.DO.Debug())
}

func (t tagAliasDo) WithContext(ctx context.Context) ITagAliasDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagAliasDo) ReadDB() ITagAliasDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagAliasDo) WriteDB() ITagAliasDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagAliasDo) Session(config *gorm.Session) ITagAliasDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagAliasDo) Clauses(conds ...clause.Expression) ITagAliasDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagAliasDo) Returning(value interface{}, columns ...string) ITagAliasDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagAliasDo) Not(conds ...gen.Condition) ITagAliasDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagAliasDo) Or(conds ...gen.Condition) ITagAliasDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagAliasDo) Select(conds ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagAliasDo) Where(conds ...gen.Condition) ITagAliasDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagAliasDo) Order(conds ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagAliasDo) Distinct(cols ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagAliasDo) Omit(cols ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagAliasDo) Join(table schema.Tabler, on ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagAliasDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagAliasDo) RightJoin(table schema.Tabler, on ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagAliasDo) Group(cols ...field.Expr) ITagAliasDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagAliasDo) Having(conds ...gen.Condition) ITagAliasDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagAliasDo) Limit(limit int) ITagAliasDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagAliasDo) Offset(offset int) ITagAliasDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagAliasDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITagAliasDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagAliasDo) Unscoped() ITagAliasDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagAliasDo) Create(values ...*model.TagAlias) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagAliasDo) CreateInBatches(values []*model.TagAlias, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagAliasDo) Save(values ...*model.TagAlias) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagAliasDo) First() (*model.TagAlias, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagAlias), nil
	}
}

func (t tagAliasDo) Take() (*model.TagAlias, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagAlias), nil
	}
}

func (t tagAliasDo) Last() (*model.TagAlias, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagAlias), nil
	}
}

func (t tagAliasDo) Find() ([]*model.TagAlias, error) {
	result, err := t.DO.Find()
	return result.([]*model.TagAlias), err
}

func (t tagAliasDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagAlias, err error) {
	buf := make([]*model.TagAlias, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagAliasDo) FindInBatches(result *[]*model.TagAlias, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagAliasDo) Attrs(attrs ...field.AssignExpr) ITagAliasDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagAliasDo) Assign(attrs ...field.AssignExpr) ITagAliasDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagAliasDo) Joins(fields ...field.RelationField) ITagAliasDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagAliasDo) Preload(fields ...field.RelationField) ITagAliasDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagAliasDo) FirstOrInit() (*model.TagAlias, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagAlias), nil
	}
}

func (t tagAliasDo) FirstOrCreate() (*model.TagAlias, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagAlias), nil
	}
}

func (t tagAliasDo) FindByPage(offset int, limit int) (result []*model.TagAlias, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagAliasDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagAliasDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagAliasDo) Delete(models ...*model.TagAlias) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagAliasDo) withDO(do gen.Dao) *tagAliasDo {
	t.DO = *do.(*gen.DO)
	return t
}
