// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newTagBindPolicy(db *gorm.DB, opts ...gen.DOOption) tagBindPolicy {
	_tagBindPolicy := tagBindPolicy{}

	_tagBindPolicy.tagBindPolicyDo.UseDB(db, opts...)
	_tagBindPolicy.tagBindPolicyDo.UseModel(&model.TagBindPolicy{})

	tableName := _tagBindPolicy.tagBindPolicyDo.TableName()
	_tagBindPolicy.ALL = field.NewAsterisk(tableName)
	_tagBindPolicy.ID = field.NewInt64(tableName, "id")
	_tagBindPolicy.TagID = field.NewInt64(tableName, "tag_id")
	_tagBindPolicy.TargetKind = field.NewString(tableName, "target_kind")
	_tagBindPolicy.CreatedAt = field.NewTime(tableName, "created_at")

	_tagBindPolicy.fillFieldMap()

	return _tagBindPolicy
}

type tagBindPolicy struct {
	tagBindPolicyDo tagBindPolicyDo

	ALL        field.Asterisk
	ID         field.Int64
	TagID      field.Int64
	TargetKind field.String
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (t tagBindPolicy) Table(newTableName string) *tagBindPolicy {
	t.tagBindPolicyDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tagBindPolicy) As(alias string) *tagBindPolicy {
	t.tagBindPolicyDo.DO = *(t.tagBindPolicyDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tagBindPolicy) updateTableName(table string) *tagBindPolicy {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt64(table, "id")
	t.TagID = field.NewInt64(table, "tag_id")
	t.TargetKind = field.NewString(table, "target_kind")
	t.CreatedAt = field.NewTime(table, "created_at")

	t.fillFieldMap()

	return t
}

func (t *tagBindPolicy) WithContext(ctx context.Context) ITagBindPolicyDo {
	return t.tagBindPolicyDo.WithContext(ctx)
}

func (t tagBindPolicy) TableName() string { return t.tagBindPolicyDo.TableName() }

func (t tagBindPolicy) Alias() string { return t.tagBindPolicyDo.Alias() }

func (t tagBindPolicy) Columns(cols ...field.Expr) gen.Columns {
	return t.tagBindPolicyDo.Columns(cols...)
}

func (t *tagBindPolicy) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tagBindPolicy) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 4)
	t.fieldMap["id"] = t.ID
	t.fieldMap["tag_id"] = t.TagID
	t.fieldMap["target_kind"] = t.TargetKind
	t.fieldMap["created_at"] = t.CreatedAt
}

func (t tagBindPolicy) clone(db *gorm.DB) tagBindPolicy {
	t.tagBindPolicyDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tagBindPolicy) replaceDB(db *gorm.DB) tagBindPolicy {
	t.tagBindPolicyDo.ReplaceDB(db)
	return t
}

type tagBindPolicyDo struct{ gen.DO }

type ITagBindPolicyDo interface {
	gen.SubQuery
	Debug() ITagBindPolicyDo
	WithContext(ctx context.Context) ITagBindPolicyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITagBindPolicyDo
	WriteDB() ITagBindPolicyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITagBindPolicyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITagBindPolicyDo
	Not(conds ...gen.Condition) ITagBindPolicyDo
	Or(conds ...gen.Condition) ITagBindPolicyDo
	Select(conds ...field.Expr) ITagBindPolicyDo
	Where(conds ...gen.Condition) ITagBindPolicyDo
	Order(conds ...field.Expr) ITagBindPolicyDo
	Distinct(cols ...field.Expr) ITagBindPolicyDo
	Omit(cols ...field.Expr) ITagBindPolicyDo
	Join(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo
	Group(cols ...field.Expr) ITagBindPolicyDo
	Having(conds ...gen.Condition) ITagBindPolicyDo
	Limit(limit int) ITagBindPolicyDo
	Offset(offset int) ITagBindPolicyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITagBindPolicyDo
	Unscoped() ITagBindPolicyDo
	Create(values ...*model.TagBindPolicy) error
	CreateInBatches(values []*model.TagBindPolicy, batchSize int) error
	Save(values ...*model.TagBindPolicy) error
	First() (*model.TagBindPolicy, error)
	Take() (*model.TagBindPolicy, error)
	Last() (*model.TagBindPolicy, error)
	Find() ([]*model.TagBindPolicy, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagBindPolicy, err error)
	FindInBatches(result *[]*model.TagBindPolicy, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TagBindPolicy) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITagBindPolicyDo
	Assign(attrs ...field.AssignExpr) ITagBindPolicyDo
	Joins(fields ...field.RelationField) ITagBindPolicyDo
	Preload(fields ...field.RelationField) ITagBindPolicyDo
	FirstOrInit() (*model.TagBindPolicy, error)
	FirstOrCreate() (*model.TagBindPolicy, error)
	FindByPage(offset int, limit int) (result []*model.TagBindPolicy, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITagBindPolicyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tagBindPolicyDo) Debug() ITagBindPolicyDo {
	return t.withDO(t.DO.Debug())
}

func (t tagBindPolicyDo) WithContext(ctx context.Context) ITagBindPolicyDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tagBindPolicyDo) ReadDB() ITagBindPolicyDo {
	return t.Clauses(dbresolver.Read)
}

func (t tagBindPolicyDo) WriteDB() ITagBindPolicyDo {
	return t.Clauses(dbresolver.Write)
}

func (t tagBindPolicyDo) Session(config *gorm.Session) ITagBindPolicyDo {
	return t.withDO(t.DO.Session(config))
}

func (t tagBindPolicyDo) Clauses(conds ...clause.Expression) ITagBindPolicyDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tagBindPolicyDo) Returning(value interface{}, columns ...string) ITagBindPolicyDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tagBindPolicyDo) Not(conds ...gen.Condition) ITagBindPolicyDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tagBindPolicyDo) Or(conds ...gen.Condition) ITagBindPolicyDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tagBindPolicyDo) Select(conds ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tagBindPolicyDo) Where(conds ...gen.Condition) ITagBindPolicyDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tagBindPolicyDo) Order(conds ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tagBindPolicyDo) Distinct(cols ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tagBindPolicyDo) Omit(cols ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tagBindPolicyDo) Join(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tagBindPolicyDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tagBindPolicyDo) RightJoin(table schema.Tabler, on ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tagBindPolicyDo) Group(cols ...field.Expr) ITagBindPolicyDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tagBindPolicyDo) Having(conds ...gen.Condition) ITagBindPolicyDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tagBindPolicyDo) Limit(limit int) ITagBindPolicyDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tagBindPolicyDo) Offset(offset int) ITagBindPolicyDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tagBindPolicyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITagBindPolicyDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tagBindPolicyDo) Unscoped() ITagBindPolicyDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tagBindPolicyDo) Create(values ...*model.TagBindPolicy) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tagBindPolicyDo) CreateInBatches(values []*model.TagBindPolicy, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tagBindPolicyDo) Save(values ...*model.TagBindPolicy) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tagBindPolicyDo) First() (*model.TagBindPolicy, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagBindPolicy), nil
	}
}

func (t tagBindPolicyDo) Take() (*model.TagBindPolicy, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagBindPolicy), nil
	}
}

func (t tagBindPolicyDo) Last() (*model.TagBindPolicy, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagBindPolicy), nil
	}
}

func (t tagBindPolicyDo) Find() ([]*model.TagBindPolicy, error) {
	result, err := t.DO.Find()
	return result.([]*model.TagBindPolicy), err
}

func (t tagBindPolicyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TagBindPolicy, err error) {
	buf := make([]*model.TagBindPolicy, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tagBindPolicyDo) FindInBatches(result *[]*model.TagBindPolicy, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tagBindPolicyDo) Attrs(attrs ...field.AssignExpr) ITagBindPolicyDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tagBindPolicyDo) Assign(attrs ...field.AssignExpr) ITagBindPolicyDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tagBindPolicyDo) Joins(fields ...field.RelationField) ITagBindPolicyDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tagBindPolicyDo) Preload(fields ...field.RelationField) ITagBindPolicyDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tagBindPolicyDo) FirstOrInit() (*model.TagBindPolicy, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagBindPolicy), nil
	}
}

func (t tagBindPolicyDo) FirstOrCreate() (*model.TagBindPolicy, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TagBindPolicy), nil
	}
}

func (t tagBindPolicyDo) FindByPage(offset int, limit int) (result []*model.TagBindPolicy, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tagBindPolicyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tagBindPolicyDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tagBindPolicyDo) Delete(models ...*model.TagBindPolicy) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tagBindPolicyDo) withDO(do gen.Dao) *tagBindPolicyDo {
	t.DO = *do.(*gen.DO)
	return t
}
