// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"omniflow-go/internal/repository/postgres/model"
)

func newUploadSession(db *gorm.DB, opts ...gen.DOOption) uploadSession {
	_uploadSession := uploadSession{}

	_uploadSession.uploadSessionDo.UseDB(db, opts...)
	_uploadSession.uploadSessionDo.UseModel(&model.UploadSession{})

	tableName := _uploadSession.uploadSessionDo.TableName()
	_uploadSession.ALL = field.NewAsterisk(tableName)
	_uploadSession.ID = field.NewString(tableName, "id")
	_uploadSession.LibraryID = field.NewInt64(tableName, "library_id")
	_uploadSession.ParentID = field.NewInt64(tableName, "parent_id")
	_uploadSession.ActorID = field.NewString(tableName, "actor_id")
	_uploadSession.StorageKey = field.NewString(tableName, "storage_key")
	_uploadSession.FileName = field.NewString(tableName, "file_name")
	_uploadSession.FileSize = field.NewInt64(tableName, "file_size")
	_uploadSession.ContentType = field.NewString(tableName, "content_type")
	_uploadSession.StorageProvider = field.NewString(tableName, "storage_provider")
	_uploadSession.Mode = field.NewString(tableName, "mode")
	_uploadSession.MinioUploadID = field.NewString(tableName, "minio_upload_id")
	_uploadSession.PartSize = field.NewInt64(tableName, "part_size")
	_uploadSession.ExpiresAt = field.NewTime(tableName, "expires_at")
	_uploadSession.CreatedAt = field.NewTime(tableName, "created_at")
	_uploadSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_uploadSession.fillFieldMap()

	return _uploadSession
}

type uploadSession struct {
	uploadSessionDo uploadSessionDo

	ALL             field.Asterisk
	ID              field.String
	LibraryID       field.Int64
	ParentID        field.Int64
	ActorID         field.String
	StorageKey      field.String
	FileName        field.String
	FileSize        field.Int64
	ContentType     field.String
	StorageProvider field.String
	Mode            field.String
	MinioUploadID   field.String
	PartSize        field.Int64
	ExpiresAt       field.Time
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (u uploadSession) Table(newTableName string) *uploadSession {
	u.uploadSessionDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u uploadSession) As(alias string) *uploadSession {
	u.uploadSessionDo.DO = *(u.uploadSessionDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *uploadSession) updateTableName(table string) *uploadSession {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.LibraryID = field.NewInt64(table, "library_id")
	u.ParentID = field.NewInt64(table, "parent_id")
	u.ActorID = field.NewString(table, "actor_id")
	u.StorageKey = field.NewString(table, "storage_key")
	u.FileName = field.NewString(table, "file_name")
	u.FileSize = field.NewInt64(table, "file_size")
	u.ContentType = field.NewString(table, "content_type")
	u.StorageProvider = field.NewString(table, "storage_provider")
	u.Mode = field.NewString(table, "mode")
	u.MinioUploadID = field.NewString(table, "minio_upload_id")
	u.PartSize = field.NewInt64(table, "part_size")
	u.ExpiresAt = field.NewTime(table, "expires_at")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *uploadSession) WithContext(ctx context.Context) IUploadSessionDo {
	return u.uploadSessionDo.WithContext(ctx)
}

func (u uploadSession) TableName() string { return u.uploadSessionDo.TableName() }

func (u uploadSession) Alias() string { return u.uploadSessionDo.Alias() }

func (u uploadSession) Columns(cols ...field.Expr) gen.Columns {
	return u.uploadSessionDo.Columns(cols...)
}

func (u *uploadSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *uploadSession) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 15)
	u.fieldMap["id"] = u.ID
	u.fieldMap["library_id"] = u.LibraryID
	u.fieldMap["parent_id"] = u.ParentID
	u.fieldMap["actor_id"] = u.ActorID
	u.fieldMap["storage_key"] = u.StorageKey
	u.fieldMap["file_name"] = u.FileName
	u.fieldMap["file_size"] = u.FileSize
	u.fieldMap["content_type"] = u.ContentType
	u.fieldMap["storage_provider"] = u.StorageProvider
	u.fieldMap["mode"] = u.Mode
	u.fieldMap["minio_upload_id"] = u.MinioUploadID
	u.fieldMap["part_size"] = u.PartSize
	u.fieldMap["expires_at"] = u.ExpiresAt
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u uploadSession) clone(db *gorm.DB) uploadSession {
	u.uploadSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u uploadSession) replaceDB(db *gorm.DB) uploadSession {
	u.uploadSessionDo.ReplaceDB(db)
	return u
}

type uploadSessionDo struct{ gen.DO }

type IUploadSessionDo interface {
	gen.SubQuery
	Debug() IUploadSessionDo
	WithContext(ctx context.Context) IUploadSessionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUploadSessionDo
	WriteDB() IUploadSessionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUploadSessionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUploadSessionDo
	Not(conds ...gen.Condition) IUploadSessionDo
	Or(conds ...gen.Condition) IUploadSessionDo
	Select(conds ...field.Expr) IUploadSessionDo
	Where(conds ...gen.Condition) IUploadSessionDo
	Order(conds ...field.Expr) IUploadSessionDo
	Distinct(cols ...field.Expr) IUploadSessionDo
	Omit(cols ...field.Expr) IUploadSessionDo
	Join(table schema.Tabler, on ...field.Expr) IUploadSessionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUploadSessionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUploadSessionDo
	Group(cols ...field.Expr) IUploadSessionDo
	Having(conds ...gen.Condition) IUploadSessionDo
	Limit(limit int) IUploadSessionDo
	Offset(offset int) IUploadSessionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUploadSessionDo
	Unscoped() IUploadSessionDo
	Create(values ...*model.UploadSession) error
	CreateInBatches(values []*model.UploadSession, batchSize int) error
	Save(values ...*model.UploadSession) error
	First() (*model.UploadSession, error)
	Take() (*model.UploadSession, error)
	Last() (*model.UploadSession, error)
	Find() ([]*model.UploadSession, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UploadSession, err error)
	FindInBatches(result *[]*model.UploadSession, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UploadSession) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUploadSessionDo
	Assign(attrs ...field.AssignExpr) IUploadSessionDo
	Joins(fields ...field.RelationField) IUploadSessionDo
	Preload(fields ...field.RelationField) IUploadSessionDo
	FirstOrInit() (*model.UploadSession, error)
	FirstOrCreate() (*model.UploadSession, error)
	FindByPage(offset int, limit int) (result []*model.UploadSession, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUploadSessionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u uploadSessionDo) Debug() IUploadSessionDo {
	return u.withDO(u.DO.Debug())
}

func (u uploadSessionDo) WithContext(ctx context.Context) IUploadSessionDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u uploadSessionDo) ReadDB() IUploadSessionDo {
	return u.Clauses(dbresolver.Read)
}

func (u uploadSessionDo) WriteDB() IUploadSessionDo {
	return u.Clauses(dbresolver.Write)
}

func (u uploadSessionDo) Session(config *gorm.Session) IUploadSessionDo {
	return u.withDO(u.DO.Session(config))
}

func (u uploadSessionDo) Clauses(conds ...clause.Expression) IUploadSessionDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u uploadSessionDo) Returning(value interface{}, columns ...string) IUploadSessionDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u uploadSessionDo) Not(conds ...gen.Condition) IUploadSessionDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u uploadSessionDo) Or(conds ...gen.Condition) IUploadSessionDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u uploadSessionDo) Select(conds ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u uploadSessionDo) Where(conds ...gen.Condition) IUploadSessionDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u uploadSessionDo) Order(conds ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u uploadSessionDo) Distinct(cols ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u uploadSessionDo) Omit(cols ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u uploadSessionDo) Join(table schema.Tabler, on ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u uploadSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u uploadSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u uploadSessionDo) Group(cols ...field.Expr) IUploadSessionDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u uploadSessionDo) Having(conds ...gen.Condition) IUploadSessionDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u uploadSessionDo) Limit(limit int) IUploadSessionDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u uploadSessionDo) Offset(offset int) IUploadSessionDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u uploadSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUploadSessionDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u uploadSessionDo) Unscoped() IUploadSessionDo {
	return u.withDO(u.DO.Unscoped())
}

func (u uploadSessionDo) Create(values ...*model.UploadSession) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u uploadSessionDo) CreateInBatches(values []*model.UploadSession, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u uploadSessionDo) Save(values ...*model.UploadSession) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u uploadSessionDo) First() (*model.UploadSession, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadSession), nil
	}
}

func (u uploadSessionDo) Take() (*model.UploadSession, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadSession), nil
	}
}

func (u uploadSessionDo) Last() (*model.UploadSession, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadSession), nil
	}
}

func (u uploadSessionDo) Find() ([]*model.UploadSession, error) {
	result, err := u.DO.Find()
	return result.([]*model.UploadSession), err
}

func (u uploadSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UploadSession, err error) {
	buf := make([]*model.UploadSession, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u uploadSessionDo) FindInBatches(result *[]*model.UploadSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u uploadSessionDo) Attrs(attrs ...field.AssignExpr) IUploadSessionDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u uploadSessionDo) Assign(attrs ...field.AssignExpr) IUploadSessionDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u uploadSessionDo) Joins(fields ...field.RelationField) IUploadSessionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u uploadSessionDo) Preload(fields ...field.RelationField) IUploadSessionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u uploadSessionDo) FirstOrInit() (*model.UploadSession, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadSession), nil
	}
}

func (u uploadSessionDo) FirstOrCreate() (*model.UploadSession, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UploadSession), nil
	}
}

func (u uploadSessionDo) FindByPage(offset int, limit int) (result []*model.UploadSession, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u uploadSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u uploadSessionDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u uploadSessionDo) Delete(models ...*model.UploadSession) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *uploadSessionDo) withDO(do gen.Dao) *uploadSessionDo {
	u.DO = *do.(*gen.DO)
	return u
}
