-- OmniFlow PostgreSQL schema patch.
--
-- Purpose:
-- 1. Extend tags from a flat type list to a multidimensional resource tag base.
-- 2. Activate node_tag_rel as the canonical node-tag binding table.
-- 3. Add tag_aliases for later search normalization and synonym matching.
--
-- Runtime compatibility:
-- - Existing type values remain valid.
-- - FILE_TAB tags are marked as ui scope; other historical tags are resource scope.
-- - Existing nodes.view_meta->tagIds values are backfilled into node_tag_rel.

BEGIN;

ALTER TABLE tags
  ADD COLUMN IF NOT EXISTS scope varchar NOT NULL DEFAULT 'resource',
  ADD COLUMN IF NOT EXISTS dimension varchar NOT NULL DEFAULT 'custom',
  ADD COLUMN IF NOT EXISTS resource_kind varchar;

UPDATE tags
SET scope = CASE WHEN type = 'FILE_TAB' THEN 'ui' ELSE 'resource' END
WHERE scope IS NULL OR btrim(scope) = '';

UPDATE tags
SET dimension = 'custom'
WHERE dimension IS NULL OR btrim(dimension) = '';

UPDATE tags
SET resource_kind = CASE type
  WHEN 'ASMR' THEN 'asmr'
  WHEN 'COMIC' THEN 'comic'
  WHEN 'VIDEO' THEN 'video'
  WHEN 'AUDIO' THEN 'audio'
  WHEN 'FILE' THEN 'file'
  WHEN 'FOLDER' THEN 'folder'
  WHEN 'GENERAL' THEN 'general'
  ELSE resource_kind
END
WHERE resource_kind IS NULL
  AND type <> 'FILE_TAB';

ALTER TABLE tags
  DROP CONSTRAINT IF EXISTS chk_tags_type,
  DROP CONSTRAINT IF EXISTS chk_tags_scope,
  DROP CONSTRAINT IF EXISTS chk_tags_dimension,
  DROP CONSTRAINT IF EXISTS chk_tags_resource_kind;

ALTER TABLE tags
  ADD CONSTRAINT chk_tags_type CHECK (type ~ '^[A-Z0-9_-]{1,64}$'),
  ADD CONSTRAINT chk_tags_scope CHECK (scope IN ('resource', 'ui')),
  ADD CONSTRAINT chk_tags_dimension CHECK (
    dimension IN (
      'genre',
      'creator',
      'character',
      'series',
      'source',
      'language',
      'region',
      'technical',
      'status',
      'custom'
    )
  ),
  ADD CONSTRAINT chk_tags_resource_kind CHECK (
    resource_kind IS NULL OR resource_kind ~ '^[a-z0-9_-]{1,64}$'
  );

DROP INDEX IF EXISTS uq_tags_scope_name_live;

CREATE UNIQUE INDEX uq_tags_scope_name_live
  ON tags (
    COALESCE(owner_user_id, 0),
    scope,
    dimension,
    COALESCE(resource_kind, ''),
    type,
    COALESCE(target_key, ''),
    name
  )
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tags_owner_scope_dimension_order
  ON tags (owner_user_id, scope, dimension, resource_kind, sort_order, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tags_scope_resource_order
  ON tags (scope, resource_kind, dimension, sort_order, id)
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS tag_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  alias varchar NOT NULL,
  normalized_alias varchar NOT NULL,
  owner_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  CONSTRAINT chk_tag_aliases_alias_not_blank CHECK (btrim(alias) <> ''),
  CONSTRAINT chk_tag_aliases_normalized_alias_not_blank CHECK (btrim(normalized_alias) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_tag_aliases_tag_alias_live
  ON tag_aliases (tag_id, normalized_alias)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tag_aliases_owner_alias
  ON tag_aliases (owner_user_id, normalized_alias)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tag_aliases_tag
  ON tag_aliases (tag_id)
  WHERE deleted_at IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_tag_aliases_updated_at'
      AND tgrelid = 'tag_aliases'::regclass
  ) THEN
    CREATE TRIGGER trg_tag_aliases_updated_at
      BEFORE UPDATE ON tag_aliases
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO node_tag_rel (node_id, tag_id, library_id)
SELECT n.id, tag_ids.tag_id, n.library_id
FROM nodes n
CROSS JOIN LATERAL (
  SELECT raw_tag_id::bigint AS tag_id
  FROM jsonb_array_elements_text(COALESCE(n.view_meta->'tagIds', '[]'::jsonb)) AS raw(raw_tag_id)
  WHERE raw_tag_id ~ '^[0-9]+$'
) AS tag_ids
JOIN tags t
  ON t.id = tag_ids.tag_id
 AND t.deleted_at IS NULL
WHERE n.deleted_at IS NULL
ON CONFLICT (node_id, tag_id) DO NOTHING;

COMMIT;
