-- OmniFlow PostgreSQL schema patch.
--
-- Purpose:
-- 1. Add tag target kinds as a stable dictionary of bindable resource units.
-- 2. Add tag bind policies, so each tag declares which resource units it can be attached to.
-- 3. Add node resource target projection for backend validation and later indexed tag search.

BEGIN;

CREATE TABLE IF NOT EXISTS tag_target_kinds (
  key varchar(64) PRIMARY KEY,
  label varchar(64) NOT NULL,
  resource_kind varchar(64) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  enabled boolean NOT NULL DEFAULT true,
  description varchar(255),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_tag_target_kinds_key CHECK (key ~ '^[a-z0-9_-]{1,64}$'),
  CONSTRAINT chk_tag_target_kinds_resource_kind CHECK (resource_kind ~ '^[a-z0-9_-]{1,64}$'),
  CONSTRAINT chk_tag_target_kinds_label_not_blank CHECK (btrim(label) <> '')
);

CREATE INDEX IF NOT EXISTS idx_tag_target_kinds_resource_order
  ON tag_target_kinds (resource_kind, sort_order, key)
  WHERE enabled = true;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'trg_tag_target_kinds_updated_at'
      AND tgrelid = 'tag_target_kinds'::regclass
  ) THEN
    CREATE TRIGGER trg_tag_target_kinds_updated_at
      BEFORE UPDATE ON tag_target_kinds
      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
  END IF;
END $$;

INSERT INTO tag_target_kinds (key, label, resource_kind, sort_order, description)
VALUES
  ('file', '文件', 'file', 10, '普通文件节点'),
  ('folder', '文件夹', 'folder', 20, '普通文件夹节点'),
  ('archive_root', '归档根目录', 'general', 30, '开启归档模式的文件夹入口'),
  ('asmr_work', 'ASMR 作品', 'asmr', 100, 'ASMR 作品文件夹'),
  ('comic_work', '漫画作品', 'comic', 110, '漫画作品文件夹'),
  ('audio_track', '音频文件', 'audio', 120, '可播放音频文件'),
  ('audio_album', '音频专辑', 'audio', 130, '音频归档或专辑文件夹'),
  ('video_file', '视频文件', 'video', 140, '可播放视频文件'),
  ('video_collection', '视频合集', 'video', 150, '视频归档或合集文件夹')
ON CONFLICT (key) DO UPDATE
SET label = EXCLUDED.label,
    resource_kind = EXCLUDED.resource_kind,
    sort_order = EXCLUDED.sort_order,
    description = EXCLUDED.description,
    enabled = true,
    updated_at = now();

CREATE TABLE IF NOT EXISTS tag_bind_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_id bigint NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  target_kind varchar(64) NOT NULL REFERENCES tag_target_kinds(key) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_tag_bind_policies_tag_target UNIQUE (tag_id, target_kind),
  CONSTRAINT chk_tag_bind_policies_target_kind CHECK (target_kind ~ '^[a-z0-9_-]{1,64}$')
);

CREATE INDEX IF NOT EXISTS idx_tag_bind_policies_target_tag
  ON tag_bind_policies (target_kind, tag_id);

CREATE INDEX IF NOT EXISTS idx_tag_bind_policies_tag
  ON tag_bind_policies (tag_id);

CREATE TABLE IF NOT EXISTS node_resource_targets (
  node_id bigint NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  library_id bigint NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,
  target_kind varchar(64) NOT NULL REFERENCES tag_target_kinds(key) ON DELETE RESTRICT,
  source varchar(64) NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (node_id, target_kind),
  CONSTRAINT chk_node_resource_targets_target_kind CHECK (target_kind ~ '^[a-z0-9_-]{1,64}$'),
  CONSTRAINT chk_node_resource_targets_source CHECK (source ~ '^[a-z0-9_-]{1,64}$')
);

CREATE INDEX IF NOT EXISTS idx_node_resource_targets_library_target_node
  ON node_resource_targets (library_id, target_kind, node_id);

CREATE INDEX IF NOT EXISTS idx_node_resource_targets_target_node
  ON node_resource_targets (target_kind, node_id);

CREATE OR REPLACE FUNCTION refresh_node_resource_targets(p_node_id bigint)
RETURNS void AS $$
BEGIN
  DELETE FROM node_resource_targets
  WHERE node_id = p_node_id;

  INSERT INTO node_resource_targets (node_id, library_id, target_kind, source)
  SELECT node_id, library_id, target_kind, source
  FROM (
    SELECT n.id AS node_id, n.library_id, 'file'::varchar AS target_kind, 'basic'::varchar AS source
    FROM nodes n
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 1

    UNION ALL

    SELECT n.id, n.library_id, 'folder', 'basic'
    FROM nodes n
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0

    UNION ALL

    SELECT n.id, n.library_id, 'archive_root', 'archive_mode'
    FROM nodes n
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0
      AND n.archive_mode = true

    UNION ALL

    SELECT n.id, n.library_id, 'asmr_work', 'builtin_type'
    FROM nodes n
    LEFT JOIN nodes p ON p.id = n.parent_id AND p.deleted_at IS NULL
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0
      AND (
        (upper(n.built_in_type) = 'ASMR' AND n.archive_mode = false)
        OR (p.archive_mode = true AND upper(p.built_in_type) = 'ASMR')
      )

    UNION ALL

    SELECT n.id, n.library_id, 'comic_work', 'builtin_type'
    FROM nodes n
    LEFT JOIN nodes p ON p.id = n.parent_id AND p.deleted_at IS NULL
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0
      AND (
        (upper(n.built_in_type) = 'COMIC' AND n.archive_mode = false)
        OR (p.archive_mode = true AND upper(p.built_in_type) = 'COMIC')
      )

    UNION ALL

    SELECT n.id, n.library_id, 'audio_album', 'builtin_type'
    FROM nodes n
    LEFT JOIN nodes p ON p.id = n.parent_id AND p.deleted_at IS NULL
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0
      AND (
        (upper(n.built_in_type) = 'AUDIO' AND n.archive_mode = false)
        OR (p.archive_mode = true AND upper(p.built_in_type) = 'AUDIO')
      )

    UNION ALL

    SELECT n.id, n.library_id, 'video_collection', 'builtin_type'
    FROM nodes n
    LEFT JOIN nodes p ON p.id = n.parent_id AND p.deleted_at IS NULL
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 0
      AND (
        (upper(n.built_in_type) = 'VIDEO' AND n.archive_mode = false)
        OR (p.archive_mode = true AND upper(p.built_in_type) = 'VIDEO')
      )

    UNION ALL

    SELECT n.id, n.library_id, 'audio_track', 'media_type'
    FROM nodes n
    LEFT JOIN node_files f ON f.file_id = n.id
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 1
      AND (
        lower(coalesce(f.mime_type, '')) LIKE 'audio/%'
        OR lower(coalesce(n.ext, '')) IN ('mp3', 'm4a', 'aac', 'flac', 'wav', 'ogg', 'opus', 'wma', 'ape', 'alac')
      )

    UNION ALL

    SELECT n.id, n.library_id, 'video_file', 'media_type'
    FROM nodes n
    LEFT JOIN node_files f ON f.file_id = n.id
    WHERE n.id = p_node_id
      AND n.deleted_at IS NULL
      AND n.node_type = 1
      AND (
        lower(coalesce(f.mime_type, '')) LIKE 'video/%'
        OR lower(coalesce(n.ext, '')) IN ('mp4', 'mkv', 'webm', 'mov', 'avi', 'wmv', 'flv', 'm4v', 'ts', 'm2ts')
      )
  ) AS targets
  ON CONFLICT (node_id, target_kind) DO UPDATE
  SET library_id = EXCLUDED.library_id,
      source = EXCLUDED.source,
      updated_at = now();
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION refresh_node_resource_targets_from_node()
RETURNS trigger AS $$
DECLARE
  child_id bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM node_resource_targets WHERE node_id = OLD.id;
    RETURN OLD;
  END IF;

  PERFORM refresh_node_resource_targets(NEW.id);

  IF TG_OP = 'UPDATE'
    AND (
      OLD.built_in_type IS DISTINCT FROM NEW.built_in_type
      OR OLD.archive_mode IS DISTINCT FROM NEW.archive_mode
      OR OLD.deleted_at IS DISTINCT FROM NEW.deleted_at
    )
  THEN
    FOR child_id IN
      SELECT id
      FROM nodes
      WHERE parent_id = NEW.id
    LOOP
      PERFORM refresh_node_resource_targets(child_id);
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION refresh_node_resource_targets_from_file()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM refresh_node_resource_targets(OLD.file_id);
    RETURN OLD;
  END IF;

  PERFORM refresh_node_resource_targets(NEW.file_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_nodes_refresh_resource_targets ON nodes;
CREATE TRIGGER trg_nodes_refresh_resource_targets
  AFTER INSERT OR UPDATE OF node_type, ext, built_in_type, archive_mode, parent_id, deleted_at
  ON nodes
  FOR EACH ROW EXECUTE FUNCTION refresh_node_resource_targets_from_node();

DROP TRIGGER IF EXISTS trg_node_files_refresh_resource_targets ON node_files;
CREATE TRIGGER trg_node_files_refresh_resource_targets
  AFTER INSERT OR UPDATE OF mime_type OR DELETE
  ON node_files
  FOR EACH ROW EXECUTE FUNCTION refresh_node_resource_targets_from_file();

INSERT INTO tag_bind_policies (tag_id, target_kind)
SELECT t.id, defaults.target_kind
FROM tags t
JOIN LATERAL (
  SELECT target_kind
  FROM (
    VALUES
      ('GENERAL', 'file'),
      ('GENERAL', 'folder'),
      ('GENERAL', 'archive_root'),
      ('ASMR', 'asmr_work'),
      ('ASMR', 'archive_root'),
      ('ASMR', 'folder'),
      ('COMIC', 'comic_work'),
      ('COMIC', 'archive_root'),
      ('COMIC', 'folder'),
      ('AUDIO', 'audio_track'),
      ('AUDIO', 'audio_album'),
      ('AUDIO', 'folder'),
      ('VIDEO', 'video_file'),
      ('VIDEO', 'video_collection'),
      ('VIDEO', 'folder'),
      ('FILE', 'file'),
      ('FOLDER', 'folder')
  ) AS mapping(tag_type, target_kind)
  WHERE mapping.tag_type = upper(t.type)
) AS defaults ON true
WHERE t.deleted_at IS NULL
  AND upper(t.type) <> 'FILE_TAB'
ON CONFLICT (tag_id, target_kind) DO NOTHING;

DO $$
DECLARE
  node_record record;
BEGIN
  FOR node_record IN
    SELECT id
    FROM nodes
  LOOP
    PERFORM refresh_node_resource_targets(node_record.id);
  END LOOP;
END $$;

COMMIT;
