#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

CONFIG_PATH="${CONFIG_PATH:-configs/config.yaml}"
OUT_PATH="${OUT_PATH:-internal/repository/postgres/query}"
MODEL_PATH="${MODEL_PATH:-internal/repository/postgres/model}"
TABLES="${TABLES:-users,libraries,nodes,node_files,storage_objects}"

go run ./internal/repository/postgres/gen \
  -config "$CONFIG_PATH" \
  -out "$OUT_PATH" \
  -model "$MODEL_PATH" \
  -tables "$TABLES" \
  "$@"

# 清理 gorm/gen 可能产生的重复头注释，保持生成文件整洁可读。
# 注意 query 目录下的 gen.go 不是 *.gen.go，也需要纳入处理范围。
find "$OUT_PATH" "$MODEL_PATH" -type f -name "*.go" | while read -r f; do
  awk '
    BEGIN { marker = "// Code generated by gorm.io/gen. DO NOT EDIT."; seen = 0 }
    {
      if ($0 == marker) {
        if (seen == 0) { print; seen = 1 }
        next
      }
      print
    }
  ' "$f" > "$f.tmp"
  mv "$f.tmp" "$f"
done
